export { default as Inline } from "./inline-query"
export { default as Variable } from "./variable-query"
export { default as ExportedVariable } from "./exported-variable-query"
export { default as Destructuring } from "./destructuring"
export { default as MJS } from "./mjs.mjs"
