module.exports = {
  program: require(`./program`),
  nodes: require(`./nodes`),
  nodesTouched: require(`./nodes-touched`),
  lastAction: require(`./last-action`),
  plugins: require(`./plugins`),
  flattenedPlugins: require(`./flattened-plugins`),
  config: require(`./config`),
  pages: require(`./pages`),
  layouts: require(`./layouts`),
  schema: require(`./schema`),
  status: require(`./status`),
  pageDataDependencies: require(`./page-data-dependencies`),
  pageComponents: require(`./page-components`),
  jobs: require(`./jobs`),
}
