# What language dictionaries should it use? Currently Typo CI supports:
# de
# en
# en_GB
# en_CA
# en_AU
# en_ZA
# es
# fr
# is
# it
# pt
# pt_BR
# sw
dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "node_modules/**/*"
  - "package-lock.json"
  - "yarn.lock"
  - "packages/**/package.json"
  - ".typo-ci.yml"
  - ".npmignore"
  - "packages/**/.npmignore"

# Any typos we should ignore?
excluded_words:
  - typoci
  - xxs
  - agadoo
  - hevc
