import { fetch, Response } from 'node-fetch';
import something from 'my-import'
import * as fs from "fs"

const usedReference = 'my cool ref';
const unusedReference = 'I hope to be removed';
const { x, y } = require('some-import');

export default function () {
  const x = new Response({})
  anotherSelfReferencedOne();

  return usedReference
}

// such a structure is being generated by regenerator-runtime
function renderPage() {
  renderPage = () => { };
}

function anotherSelfReferencedOne() {
  anotherSelfReferencedOne = () => { };
}

export async function getServerData() {
  const data = await fetch('https://example.com');
  const file = fs.readFileSync('./unknown.tmp.json', 'utf8')
  renderPage();
  anotherSelfReferencedOne();

  return {
    props: {
      x,
      y,
      file,
      data: await data.json(),
      unusedReference,
      test: something(),
    }

  }
}

export function config() {
  return {
    pageContext: {
      env: 'test',
      unusedReference,
    },
  }
}

export function anotherFunction() {
  return "test"
}
