// flow-typed signature: 613700e9be59614d50f223b3c6db5aed
// flow-typed version: <<STUB>>/ava-http_v^0.2.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ava-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ava-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ava-http/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ava-http/dist/index.js' {
  declare module.exports: $Exports<'ava-http/dist/index'>;
}
