// flow-typed signature: 0792102294242b8fe67bf2216d40ddfa
// flow-typed version: <<STUB>>/boom_v^2.7.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'boom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boom/lib/index' {
  declare module.exports: any;
}

declare module 'boom/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boom/lib/index.js' {
  declare module.exports: $Exports<'boom/lib/index'>;
}
declare module 'boom/test/index.js' {
  declare module.exports: $Exports<'boom/test/index'>;
}
