// flow-typed signature: 62f5cb405b4ce479a7b07d0377bd8fc4
// flow-typed version: <<STUB>>/cjsx-loader_v^3.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cjsx-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cjsx-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cjsx-loader/index' {
  declare module.exports: $Exports<'cjsx-loader'>;
}
declare module 'cjsx-loader/index.js' {
  declare module.exports: $Exports<'cjsx-loader'>;
}
