// flow-typed signature: cdeddb7483bcd0035c59ba6fe01bc547
// flow-typed version: <<STUB>>/eslint-plugin-flow-vars_v^0.5.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flow-vars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flow-vars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-flow-vars/define-flow-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow-vars/use-flow-type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-flow-vars/define-flow-type.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-vars/define-flow-type'>;
}
declare module 'eslint-plugin-flow-vars/index' {
  declare module.exports: $Exports<'eslint-plugin-flow-vars'>;
}
declare module 'eslint-plugin-flow-vars/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-vars'>;
}
declare module 'eslint-plugin-flow-vars/use-flow-type.js' {
  declare module.exports: $Exports<'eslint-plugin-flow-vars/use-flow-type'>;
}
