// flow-typed signature: bd7727d6f5e1a9dc1df8bbbd038d3c48
// flow-typed version: <<STUB>>/hapi_v^8.5.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hapi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hapi/lib/auth' {
  declare module.exports: any;
}

declare module 'hapi/lib/connection' {
  declare module.exports: any;
}

declare module 'hapi/lib/defaults' {
  declare module.exports: any;
}

declare module 'hapi/lib/handler' {
  declare module.exports: any;
}

declare module 'hapi/lib/index' {
  declare module.exports: any;
}

declare module 'hapi/lib/methods' {
  declare module.exports: any;
}

declare module 'hapi/lib/plugin' {
  declare module.exports: any;
}

declare module 'hapi/lib/protect' {
  declare module.exports: any;
}

declare module 'hapi/lib/reply' {
  declare module.exports: any;
}

declare module 'hapi/lib/request' {
  declare module.exports: any;
}

declare module 'hapi/lib/response' {
  declare module.exports: any;
}

declare module 'hapi/lib/route' {
  declare module.exports: any;
}

declare module 'hapi/lib/schema' {
  declare module.exports: any;
}

declare module 'hapi/lib/server' {
  declare module.exports: any;
}

declare module 'hapi/lib/transmit' {
  declare module.exports: any;
}

declare module 'hapi/lib/validation' {
  declare module.exports: any;
}

declare module 'hapi/test/auth' {
  declare module.exports: any;
}

declare module 'hapi/test/connection' {
  declare module.exports: any;
}

declare module 'hapi/test/handler' {
  declare module.exports: any;
}

declare module 'hapi/test/methods' {
  declare module.exports: any;
}

declare module 'hapi/test/payload' {
  declare module.exports: any;
}

declare module 'hapi/test/plugin' {
  declare module.exports: any;
}

declare module 'hapi/test/protect' {
  declare module.exports: any;
}

declare module 'hapi/test/reply' {
  declare module.exports: any;
}

declare module 'hapi/test/request' {
  declare module.exports: any;
}

declare module 'hapi/test/response' {
  declare module.exports: any;
}

declare module 'hapi/test/route' {
  declare module.exports: any;
}

declare module 'hapi/test/security' {
  declare module.exports: any;
}

declare module 'hapi/test/server' {
  declare module.exports: any;
}

declare module 'hapi/test/state' {
  declare module.exports: any;
}

declare module 'hapi/test/transmit' {
  declare module.exports: any;
}

declare module 'hapi/test/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hapi/lib/auth.js' {
  declare module.exports: $Exports<'hapi/lib/auth'>;
}
declare module 'hapi/lib/connection.js' {
  declare module.exports: $Exports<'hapi/lib/connection'>;
}
declare module 'hapi/lib/defaults.js' {
  declare module.exports: $Exports<'hapi/lib/defaults'>;
}
declare module 'hapi/lib/handler.js' {
  declare module.exports: $Exports<'hapi/lib/handler'>;
}
declare module 'hapi/lib/index.js' {
  declare module.exports: $Exports<'hapi/lib/index'>;
}
declare module 'hapi/lib/methods.js' {
  declare module.exports: $Exports<'hapi/lib/methods'>;
}
declare module 'hapi/lib/plugin.js' {
  declare module.exports: $Exports<'hapi/lib/plugin'>;
}
declare module 'hapi/lib/protect.js' {
  declare module.exports: $Exports<'hapi/lib/protect'>;
}
declare module 'hapi/lib/reply.js' {
  declare module.exports: $Exports<'hapi/lib/reply'>;
}
declare module 'hapi/lib/request.js' {
  declare module.exports: $Exports<'hapi/lib/request'>;
}
declare module 'hapi/lib/response.js' {
  declare module.exports: $Exports<'hapi/lib/response'>;
}
declare module 'hapi/lib/route.js' {
  declare module.exports: $Exports<'hapi/lib/route'>;
}
declare module 'hapi/lib/schema.js' {
  declare module.exports: $Exports<'hapi/lib/schema'>;
}
declare module 'hapi/lib/server.js' {
  declare module.exports: $Exports<'hapi/lib/server'>;
}
declare module 'hapi/lib/transmit.js' {
  declare module.exports: $Exports<'hapi/lib/transmit'>;
}
declare module 'hapi/lib/validation.js' {
  declare module.exports: $Exports<'hapi/lib/validation'>;
}
declare module 'hapi/test/auth.js' {
  declare module.exports: $Exports<'hapi/test/auth'>;
}
declare module 'hapi/test/connection.js' {
  declare module.exports: $Exports<'hapi/test/connection'>;
}
declare module 'hapi/test/handler.js' {
  declare module.exports: $Exports<'hapi/test/handler'>;
}
declare module 'hapi/test/methods.js' {
  declare module.exports: $Exports<'hapi/test/methods'>;
}
declare module 'hapi/test/payload.js' {
  declare module.exports: $Exports<'hapi/test/payload'>;
}
declare module 'hapi/test/plugin.js' {
  declare module.exports: $Exports<'hapi/test/plugin'>;
}
declare module 'hapi/test/protect.js' {
  declare module.exports: $Exports<'hapi/test/protect'>;
}
declare module 'hapi/test/reply.js' {
  declare module.exports: $Exports<'hapi/test/reply'>;
}
declare module 'hapi/test/request.js' {
  declare module.exports: $Exports<'hapi/test/request'>;
}
declare module 'hapi/test/response.js' {
  declare module.exports: $Exports<'hapi/test/response'>;
}
declare module 'hapi/test/route.js' {
  declare module.exports: $Exports<'hapi/test/route'>;
}
declare module 'hapi/test/security.js' {
  declare module.exports: $Exports<'hapi/test/security'>;
}
declare module 'hapi/test/server.js' {
  declare module.exports: $Exports<'hapi/test/server'>;
}
declare module 'hapi/test/state.js' {
  declare module.exports: $Exports<'hapi/test/state'>;
}
declare module 'hapi/test/transmit.js' {
  declare module.exports: $Exports<'hapi/test/transmit'>;
}
declare module 'hapi/test/validation.js' {
  declare module.exports: $Exports<'hapi/test/validation'>;
}
