// flow-typed signature: 54cb6599c8ef902aec0751e404289114
// flow-typed version: <<STUB>>/highlight.js_v^9.6.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highlight.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'highlight.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highlight.js/lib/highlight' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/index' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/1c' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/abnf' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/accesslog' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/actionscript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/ada' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/apache' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/applescript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/arduino' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/armasm' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/asciidoc' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/aspectj' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/autohotkey' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/autoit' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/avrasm' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/awk' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/axapta' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/bash' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/basic' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/bnf' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/brainfuck' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/cal' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/capnproto' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/ceylon' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/clojure-repl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/clojure' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/cmake' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/coffeescript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/coq' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/cos' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/cpp' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/crmsh' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/crystal' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/cs' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/csp' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/css' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/d' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/dart' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/delphi' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/diff' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/django' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/dns' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/dockerfile' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/dos' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/dsconfig' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/dts' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/dust' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/ebnf' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/elixir' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/elm' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/erb' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/erlang-repl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/erlang' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/excel' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/fix' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/fortran' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/fsharp' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/gams' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/gauss' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/gcode' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/gherkin' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/glsl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/go' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/golo' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/gradle' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/groovy' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/haml' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/handlebars' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/haskell' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/haxe' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/hsp' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/htmlbars' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/http' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/inform7' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/ini' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/irpf90' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/java' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/javascript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/json' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/julia' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/kotlin' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/lasso' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/ldif' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/less' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/lisp' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/livecodeserver' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/livescript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/lsl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/lua' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/makefile' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/markdown' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/mathematica' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/matlab' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/maxima' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/mel' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/mercury' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/mipsasm' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/mizar' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/mojolicious' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/monkey' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/moonscript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/nginx' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/nimrod' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/nix' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/nsis' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/objectivec' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/ocaml' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/openscad' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/oxygene' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/parser3' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/perl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/pf' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/php' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/pony' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/powershell' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/processing' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/profile' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/prolog' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/protobuf' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/puppet' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/purebasic' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/python' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/q' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/qml' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/r' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/rib' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/roboconf' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/rsl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/ruby' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/ruleslanguage' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/rust' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/scala' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/scheme' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/scilab' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/scss' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/smali' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/smalltalk' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/sml' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/sqf' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/sql' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/stan' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/stata' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/step21' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/stylus' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/subunit' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/swift' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/taggerscript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/tap' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/tcl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/tex' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/thrift' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/tp' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/twig' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/typescript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/vala' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/vbnet' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/vbscript-html' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/vbscript' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/verilog' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/vhdl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/vim' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/x86asm' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/xl' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/xml' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/xquery' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/yaml' {
  declare module.exports: any;
}

declare module 'highlight.js/lib/languages/zephir' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highlight.js/lib/highlight.js' {
  declare module.exports: $Exports<'highlight.js/lib/highlight'>;
}
declare module 'highlight.js/lib/index.js' {
  declare module.exports: $Exports<'highlight.js/lib/index'>;
}
declare module 'highlight.js/lib/languages/1c.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/1c'>;
}
declare module 'highlight.js/lib/languages/abnf.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/abnf'>;
}
declare module 'highlight.js/lib/languages/accesslog.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/accesslog'>;
}
declare module 'highlight.js/lib/languages/actionscript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/actionscript'>;
}
declare module 'highlight.js/lib/languages/ada.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/ada'>;
}
declare module 'highlight.js/lib/languages/apache.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/apache'>;
}
declare module 'highlight.js/lib/languages/applescript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/applescript'>;
}
declare module 'highlight.js/lib/languages/arduino.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/arduino'>;
}
declare module 'highlight.js/lib/languages/armasm.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/armasm'>;
}
declare module 'highlight.js/lib/languages/asciidoc.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/asciidoc'>;
}
declare module 'highlight.js/lib/languages/aspectj.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/aspectj'>;
}
declare module 'highlight.js/lib/languages/autohotkey.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/autohotkey'>;
}
declare module 'highlight.js/lib/languages/autoit.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/autoit'>;
}
declare module 'highlight.js/lib/languages/avrasm.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/avrasm'>;
}
declare module 'highlight.js/lib/languages/awk.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/awk'>;
}
declare module 'highlight.js/lib/languages/axapta.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/axapta'>;
}
declare module 'highlight.js/lib/languages/bash.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/bash'>;
}
declare module 'highlight.js/lib/languages/basic.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/basic'>;
}
declare module 'highlight.js/lib/languages/bnf.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/bnf'>;
}
declare module 'highlight.js/lib/languages/brainfuck.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/brainfuck'>;
}
declare module 'highlight.js/lib/languages/cal.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/cal'>;
}
declare module 'highlight.js/lib/languages/capnproto.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/capnproto'>;
}
declare module 'highlight.js/lib/languages/ceylon.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/ceylon'>;
}
declare module 'highlight.js/lib/languages/clojure-repl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/clojure-repl'>;
}
declare module 'highlight.js/lib/languages/clojure.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/clojure'>;
}
declare module 'highlight.js/lib/languages/cmake.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/cmake'>;
}
declare module 'highlight.js/lib/languages/coffeescript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/coffeescript'>;
}
declare module 'highlight.js/lib/languages/coq.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/coq'>;
}
declare module 'highlight.js/lib/languages/cos.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/cos'>;
}
declare module 'highlight.js/lib/languages/cpp.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/cpp'>;
}
declare module 'highlight.js/lib/languages/crmsh.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/crmsh'>;
}
declare module 'highlight.js/lib/languages/crystal.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/crystal'>;
}
declare module 'highlight.js/lib/languages/cs.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/cs'>;
}
declare module 'highlight.js/lib/languages/csp.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/csp'>;
}
declare module 'highlight.js/lib/languages/css.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/css'>;
}
declare module 'highlight.js/lib/languages/d.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/d'>;
}
declare module 'highlight.js/lib/languages/dart.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/dart'>;
}
declare module 'highlight.js/lib/languages/delphi.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/delphi'>;
}
declare module 'highlight.js/lib/languages/diff.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/diff'>;
}
declare module 'highlight.js/lib/languages/django.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/django'>;
}
declare module 'highlight.js/lib/languages/dns.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/dns'>;
}
declare module 'highlight.js/lib/languages/dockerfile.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/dockerfile'>;
}
declare module 'highlight.js/lib/languages/dos.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/dos'>;
}
declare module 'highlight.js/lib/languages/dsconfig.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/dsconfig'>;
}
declare module 'highlight.js/lib/languages/dts.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/dts'>;
}
declare module 'highlight.js/lib/languages/dust.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/dust'>;
}
declare module 'highlight.js/lib/languages/ebnf.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/ebnf'>;
}
declare module 'highlight.js/lib/languages/elixir.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/elixir'>;
}
declare module 'highlight.js/lib/languages/elm.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/elm'>;
}
declare module 'highlight.js/lib/languages/erb.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/erb'>;
}
declare module 'highlight.js/lib/languages/erlang-repl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/erlang-repl'>;
}
declare module 'highlight.js/lib/languages/erlang.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/erlang'>;
}
declare module 'highlight.js/lib/languages/excel.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/excel'>;
}
declare module 'highlight.js/lib/languages/fix.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/fix'>;
}
declare module 'highlight.js/lib/languages/fortran.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/fortran'>;
}
declare module 'highlight.js/lib/languages/fsharp.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/fsharp'>;
}
declare module 'highlight.js/lib/languages/gams.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/gams'>;
}
declare module 'highlight.js/lib/languages/gauss.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/gauss'>;
}
declare module 'highlight.js/lib/languages/gcode.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/gcode'>;
}
declare module 'highlight.js/lib/languages/gherkin.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/gherkin'>;
}
declare module 'highlight.js/lib/languages/glsl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/glsl'>;
}
declare module 'highlight.js/lib/languages/go.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/go'>;
}
declare module 'highlight.js/lib/languages/golo.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/golo'>;
}
declare module 'highlight.js/lib/languages/gradle.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/gradle'>;
}
declare module 'highlight.js/lib/languages/groovy.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/groovy'>;
}
declare module 'highlight.js/lib/languages/haml.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/haml'>;
}
declare module 'highlight.js/lib/languages/handlebars.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/handlebars'>;
}
declare module 'highlight.js/lib/languages/haskell.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/haskell'>;
}
declare module 'highlight.js/lib/languages/haxe.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/haxe'>;
}
declare module 'highlight.js/lib/languages/hsp.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/hsp'>;
}
declare module 'highlight.js/lib/languages/htmlbars.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/htmlbars'>;
}
declare module 'highlight.js/lib/languages/http.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/http'>;
}
declare module 'highlight.js/lib/languages/inform7.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/inform7'>;
}
declare module 'highlight.js/lib/languages/ini.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/ini'>;
}
declare module 'highlight.js/lib/languages/irpf90.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/irpf90'>;
}
declare module 'highlight.js/lib/languages/java.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/java'>;
}
declare module 'highlight.js/lib/languages/javascript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/javascript'>;
}
declare module 'highlight.js/lib/languages/json.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/json'>;
}
declare module 'highlight.js/lib/languages/julia.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/julia'>;
}
declare module 'highlight.js/lib/languages/kotlin.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/kotlin'>;
}
declare module 'highlight.js/lib/languages/lasso.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/lasso'>;
}
declare module 'highlight.js/lib/languages/ldif.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/ldif'>;
}
declare module 'highlight.js/lib/languages/less.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/less'>;
}
declare module 'highlight.js/lib/languages/lisp.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/lisp'>;
}
declare module 'highlight.js/lib/languages/livecodeserver.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/livecodeserver'>;
}
declare module 'highlight.js/lib/languages/livescript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/livescript'>;
}
declare module 'highlight.js/lib/languages/lsl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/lsl'>;
}
declare module 'highlight.js/lib/languages/lua.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/lua'>;
}
declare module 'highlight.js/lib/languages/makefile.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/makefile'>;
}
declare module 'highlight.js/lib/languages/markdown.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/markdown'>;
}
declare module 'highlight.js/lib/languages/mathematica.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/mathematica'>;
}
declare module 'highlight.js/lib/languages/matlab.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/matlab'>;
}
declare module 'highlight.js/lib/languages/maxima.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/maxima'>;
}
declare module 'highlight.js/lib/languages/mel.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/mel'>;
}
declare module 'highlight.js/lib/languages/mercury.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/mercury'>;
}
declare module 'highlight.js/lib/languages/mipsasm.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/mipsasm'>;
}
declare module 'highlight.js/lib/languages/mizar.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/mizar'>;
}
declare module 'highlight.js/lib/languages/mojolicious.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/mojolicious'>;
}
declare module 'highlight.js/lib/languages/monkey.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/monkey'>;
}
declare module 'highlight.js/lib/languages/moonscript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/moonscript'>;
}
declare module 'highlight.js/lib/languages/nginx.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/nginx'>;
}
declare module 'highlight.js/lib/languages/nimrod.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/nimrod'>;
}
declare module 'highlight.js/lib/languages/nix.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/nix'>;
}
declare module 'highlight.js/lib/languages/nsis.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/nsis'>;
}
declare module 'highlight.js/lib/languages/objectivec.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/objectivec'>;
}
declare module 'highlight.js/lib/languages/ocaml.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/ocaml'>;
}
declare module 'highlight.js/lib/languages/openscad.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/openscad'>;
}
declare module 'highlight.js/lib/languages/oxygene.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/oxygene'>;
}
declare module 'highlight.js/lib/languages/parser3.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/parser3'>;
}
declare module 'highlight.js/lib/languages/perl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/perl'>;
}
declare module 'highlight.js/lib/languages/pf.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/pf'>;
}
declare module 'highlight.js/lib/languages/php.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/php'>;
}
declare module 'highlight.js/lib/languages/pony.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/pony'>;
}
declare module 'highlight.js/lib/languages/powershell.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/powershell'>;
}
declare module 'highlight.js/lib/languages/processing.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/processing'>;
}
declare module 'highlight.js/lib/languages/profile.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/profile'>;
}
declare module 'highlight.js/lib/languages/prolog.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/prolog'>;
}
declare module 'highlight.js/lib/languages/protobuf.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/protobuf'>;
}
declare module 'highlight.js/lib/languages/puppet.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/puppet'>;
}
declare module 'highlight.js/lib/languages/purebasic.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/purebasic'>;
}
declare module 'highlight.js/lib/languages/python.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/python'>;
}
declare module 'highlight.js/lib/languages/q.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/q'>;
}
declare module 'highlight.js/lib/languages/qml.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/qml'>;
}
declare module 'highlight.js/lib/languages/r.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/r'>;
}
declare module 'highlight.js/lib/languages/rib.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/rib'>;
}
declare module 'highlight.js/lib/languages/roboconf.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/roboconf'>;
}
declare module 'highlight.js/lib/languages/rsl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/rsl'>;
}
declare module 'highlight.js/lib/languages/ruby.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/ruby'>;
}
declare module 'highlight.js/lib/languages/ruleslanguage.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/ruleslanguage'>;
}
declare module 'highlight.js/lib/languages/rust.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/rust'>;
}
declare module 'highlight.js/lib/languages/scala.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/scala'>;
}
declare module 'highlight.js/lib/languages/scheme.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/scheme'>;
}
declare module 'highlight.js/lib/languages/scilab.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/scilab'>;
}
declare module 'highlight.js/lib/languages/scss.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/scss'>;
}
declare module 'highlight.js/lib/languages/smali.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/smali'>;
}
declare module 'highlight.js/lib/languages/smalltalk.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/smalltalk'>;
}
declare module 'highlight.js/lib/languages/sml.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/sml'>;
}
declare module 'highlight.js/lib/languages/sqf.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/sqf'>;
}
declare module 'highlight.js/lib/languages/sql.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/sql'>;
}
declare module 'highlight.js/lib/languages/stan.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/stan'>;
}
declare module 'highlight.js/lib/languages/stata.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/stata'>;
}
declare module 'highlight.js/lib/languages/step21.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/step21'>;
}
declare module 'highlight.js/lib/languages/stylus.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/stylus'>;
}
declare module 'highlight.js/lib/languages/subunit.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/subunit'>;
}
declare module 'highlight.js/lib/languages/swift.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/swift'>;
}
declare module 'highlight.js/lib/languages/taggerscript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/taggerscript'>;
}
declare module 'highlight.js/lib/languages/tap.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/tap'>;
}
declare module 'highlight.js/lib/languages/tcl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/tcl'>;
}
declare module 'highlight.js/lib/languages/tex.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/tex'>;
}
declare module 'highlight.js/lib/languages/thrift.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/thrift'>;
}
declare module 'highlight.js/lib/languages/tp.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/tp'>;
}
declare module 'highlight.js/lib/languages/twig.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/twig'>;
}
declare module 'highlight.js/lib/languages/typescript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/typescript'>;
}
declare module 'highlight.js/lib/languages/vala.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/vala'>;
}
declare module 'highlight.js/lib/languages/vbnet.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/vbnet'>;
}
declare module 'highlight.js/lib/languages/vbscript-html.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/vbscript-html'>;
}
declare module 'highlight.js/lib/languages/vbscript.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/vbscript'>;
}
declare module 'highlight.js/lib/languages/verilog.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/verilog'>;
}
declare module 'highlight.js/lib/languages/vhdl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/vhdl'>;
}
declare module 'highlight.js/lib/languages/vim.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/vim'>;
}
declare module 'highlight.js/lib/languages/x86asm.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/x86asm'>;
}
declare module 'highlight.js/lib/languages/xl.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/xl'>;
}
declare module 'highlight.js/lib/languages/xml.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/xml'>;
}
declare module 'highlight.js/lib/languages/xquery.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/xquery'>;
}
declare module 'highlight.js/lib/languages/yaml.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/yaml'>;
}
declare module 'highlight.js/lib/languages/zephir.js' {
  declare module.exports: $Exports<'highlight.js/lib/languages/zephir'>;
}
