// flow-typed signature: 03321368d6bb48abe9763f7b012754de
// flow-typed version: <<STUB>>/joi_v^9.1.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'joi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'joi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'joi/lib/alternatives' {
  declare module.exports: any;
}

declare module 'joi/lib/any' {
  declare module.exports: any;
}

declare module 'joi/lib/array' {
  declare module.exports: any;
}

declare module 'joi/lib/binary' {
  declare module.exports: any;
}

declare module 'joi/lib/boolean' {
  declare module.exports: any;
}

declare module 'joi/lib/cast' {
  declare module.exports: any;
}

declare module 'joi/lib/date' {
  declare module.exports: any;
}

declare module 'joi/lib/errors' {
  declare module.exports: any;
}

declare module 'joi/lib/index' {
  declare module.exports: any;
}

declare module 'joi/lib/language' {
  declare module.exports: any;
}

declare module 'joi/lib/lazy' {
  declare module.exports: any;
}

declare module 'joi/lib/number' {
  declare module.exports: any;
}

declare module 'joi/lib/object' {
  declare module.exports: any;
}

declare module 'joi/lib/ref' {
  declare module.exports: any;
}

declare module 'joi/lib/schemas' {
  declare module.exports: any;
}

declare module 'joi/lib/string' {
  declare module.exports: any;
}

declare module 'joi/lib/string/ip' {
  declare module.exports: any;
}

declare module 'joi/lib/string/rfc3986' {
  declare module.exports: any;
}

declare module 'joi/lib/string/uri' {
  declare module.exports: any;
}

// Filename aliases
declare module 'joi/lib/alternatives.js' {
  declare module.exports: $Exports<'joi/lib/alternatives'>;
}
declare module 'joi/lib/any.js' {
  declare module.exports: $Exports<'joi/lib/any'>;
}
declare module 'joi/lib/array.js' {
  declare module.exports: $Exports<'joi/lib/array'>;
}
declare module 'joi/lib/binary.js' {
  declare module.exports: $Exports<'joi/lib/binary'>;
}
declare module 'joi/lib/boolean.js' {
  declare module.exports: $Exports<'joi/lib/boolean'>;
}
declare module 'joi/lib/cast.js' {
  declare module.exports: $Exports<'joi/lib/cast'>;
}
declare module 'joi/lib/date.js' {
  declare module.exports: $Exports<'joi/lib/date'>;
}
declare module 'joi/lib/errors.js' {
  declare module.exports: $Exports<'joi/lib/errors'>;
}
declare module 'joi/lib/index.js' {
  declare module.exports: $Exports<'joi/lib/index'>;
}
declare module 'joi/lib/language.js' {
  declare module.exports: $Exports<'joi/lib/language'>;
}
declare module 'joi/lib/lazy.js' {
  declare module.exports: $Exports<'joi/lib/lazy'>;
}
declare module 'joi/lib/number.js' {
  declare module.exports: $Exports<'joi/lib/number'>;
}
declare module 'joi/lib/object.js' {
  declare module.exports: $Exports<'joi/lib/object'>;
}
declare module 'joi/lib/ref.js' {
  declare module.exports: $Exports<'joi/lib/ref'>;
}
declare module 'joi/lib/schemas.js' {
  declare module.exports: $Exports<'joi/lib/schemas'>;
}
declare module 'joi/lib/string.js' {
  declare module.exports: $Exports<'joi/lib/string'>;
}
declare module 'joi/lib/string/ip.js' {
  declare module.exports: $Exports<'joi/lib/string/ip'>;
}
declare module 'joi/lib/string/rfc3986.js' {
  declare module.exports: $Exports<'joi/lib/string/rfc3986'>;
}
declare module 'joi/lib/string/uri.js' {
  declare module.exports: $Exports<'joi/lib/string/uri'>;
}
