// flow-typed signature: e48c8af2b9af2b2f1dc762af5c22f0c2
// flow-typed version: <<STUB>>/json5_v^0.5.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'json5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json5/lib/cli' {
  declare module.exports: any;
}

declare module 'json5/lib/json5' {
  declare module.exports: any;
}

declare module 'json5/lib/require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json5/lib/cli.js' {
  declare module.exports: $Exports<'json5/lib/cli'>;
}
declare module 'json5/lib/json5.js' {
  declare module.exports: $Exports<'json5/lib/json5'>;
}
declare module 'json5/lib/require.js' {
  declare module.exports: $Exports<'json5/lib/require'>;
}
