// flow-typed signature: 4056df4c03eed19214318a428c50f183
// flow-typed version: <<STUB>>/markdown-it_v^7.0.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-it/bin/markdown-it' {
  declare module.exports: any;
}

declare module 'markdown-it/dist/markdown-it' {
  declare module.exports: any;
}

declare module 'markdown-it/dist/markdown-it.min' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/common/entities' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/common/html_blocks' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/common/html_re' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/common/utils' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/helpers/index' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/helpers/parse_link_destination' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/helpers/parse_link_label' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/helpers/parse_link_title' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/index' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/parser_block' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/parser_core' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/parser_inline' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/presets/commonmark' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/presets/default' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/presets/zero' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/renderer' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/ruler' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/blockquote' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/code' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/fence' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/heading' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/hr' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/html_block' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/lheading' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/list' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/paragraph' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/reference' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/state_block' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_block/table' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_core/block' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_core/inline' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_core/linkify' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_core/normalize' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_core/replacements' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_core/smartquotes' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_core/state_core' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/autolink' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/backticks' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/balance_pairs' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/emphasis' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/entity' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/escape' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/html_inline' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/image' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/link' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/newline' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/state_inline' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/strikethrough' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/text_collapse' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/rules_inline/text' {
  declare module.exports: any;
}

declare module 'markdown-it/lib/token' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-it/bin/markdown-it.js' {
  declare module.exports: $Exports<'markdown-it/bin/markdown-it'>;
}
declare module 'markdown-it/dist/markdown-it.js' {
  declare module.exports: $Exports<'markdown-it/dist/markdown-it'>;
}
declare module 'markdown-it/dist/markdown-it.min.js' {
  declare module.exports: $Exports<'markdown-it/dist/markdown-it.min'>;
}
declare module 'markdown-it/index' {
  declare module.exports: $Exports<'markdown-it'>;
}
declare module 'markdown-it/index.js' {
  declare module.exports: $Exports<'markdown-it'>;
}
declare module 'markdown-it/lib/common/entities.js' {
  declare module.exports: $Exports<'markdown-it/lib/common/entities'>;
}
declare module 'markdown-it/lib/common/html_blocks.js' {
  declare module.exports: $Exports<'markdown-it/lib/common/html_blocks'>;
}
declare module 'markdown-it/lib/common/html_re.js' {
  declare module.exports: $Exports<'markdown-it/lib/common/html_re'>;
}
declare module 'markdown-it/lib/common/utils.js' {
  declare module.exports: $Exports<'markdown-it/lib/common/utils'>;
}
declare module 'markdown-it/lib/helpers/index.js' {
  declare module.exports: $Exports<'markdown-it/lib/helpers/index'>;
}
declare module 'markdown-it/lib/helpers/parse_link_destination.js' {
  declare module.exports: $Exports<'markdown-it/lib/helpers/parse_link_destination'>;
}
declare module 'markdown-it/lib/helpers/parse_link_label.js' {
  declare module.exports: $Exports<'markdown-it/lib/helpers/parse_link_label'>;
}
declare module 'markdown-it/lib/helpers/parse_link_title.js' {
  declare module.exports: $Exports<'markdown-it/lib/helpers/parse_link_title'>;
}
declare module 'markdown-it/lib/index.js' {
  declare module.exports: $Exports<'markdown-it/lib/index'>;
}
declare module 'markdown-it/lib/parser_block.js' {
  declare module.exports: $Exports<'markdown-it/lib/parser_block'>;
}
declare module 'markdown-it/lib/parser_core.js' {
  declare module.exports: $Exports<'markdown-it/lib/parser_core'>;
}
declare module 'markdown-it/lib/parser_inline.js' {
  declare module.exports: $Exports<'markdown-it/lib/parser_inline'>;
}
declare module 'markdown-it/lib/presets/commonmark.js' {
  declare module.exports: $Exports<'markdown-it/lib/presets/commonmark'>;
}
declare module 'markdown-it/lib/presets/default.js' {
  declare module.exports: $Exports<'markdown-it/lib/presets/default'>;
}
declare module 'markdown-it/lib/presets/zero.js' {
  declare module.exports: $Exports<'markdown-it/lib/presets/zero'>;
}
declare module 'markdown-it/lib/renderer.js' {
  declare module.exports: $Exports<'markdown-it/lib/renderer'>;
}
declare module 'markdown-it/lib/ruler.js' {
  declare module.exports: $Exports<'markdown-it/lib/ruler'>;
}
declare module 'markdown-it/lib/rules_block/blockquote.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/blockquote'>;
}
declare module 'markdown-it/lib/rules_block/code.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/code'>;
}
declare module 'markdown-it/lib/rules_block/fence.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/fence'>;
}
declare module 'markdown-it/lib/rules_block/heading.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/heading'>;
}
declare module 'markdown-it/lib/rules_block/hr.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/hr'>;
}
declare module 'markdown-it/lib/rules_block/html_block.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/html_block'>;
}
declare module 'markdown-it/lib/rules_block/lheading.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/lheading'>;
}
declare module 'markdown-it/lib/rules_block/list.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/list'>;
}
declare module 'markdown-it/lib/rules_block/paragraph.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/paragraph'>;
}
declare module 'markdown-it/lib/rules_block/reference.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/reference'>;
}
declare module 'markdown-it/lib/rules_block/state_block.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/state_block'>;
}
declare module 'markdown-it/lib/rules_block/table.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_block/table'>;
}
declare module 'markdown-it/lib/rules_core/block.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_core/block'>;
}
declare module 'markdown-it/lib/rules_core/inline.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_core/inline'>;
}
declare module 'markdown-it/lib/rules_core/linkify.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_core/linkify'>;
}
declare module 'markdown-it/lib/rules_core/normalize.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_core/normalize'>;
}
declare module 'markdown-it/lib/rules_core/replacements.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_core/replacements'>;
}
declare module 'markdown-it/lib/rules_core/smartquotes.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_core/smartquotes'>;
}
declare module 'markdown-it/lib/rules_core/state_core.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_core/state_core'>;
}
declare module 'markdown-it/lib/rules_inline/autolink.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/autolink'>;
}
declare module 'markdown-it/lib/rules_inline/backticks.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/backticks'>;
}
declare module 'markdown-it/lib/rules_inline/balance_pairs.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/balance_pairs'>;
}
declare module 'markdown-it/lib/rules_inline/emphasis.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/emphasis'>;
}
declare module 'markdown-it/lib/rules_inline/entity.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/entity'>;
}
declare module 'markdown-it/lib/rules_inline/escape.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/escape'>;
}
declare module 'markdown-it/lib/rules_inline/html_inline.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/html_inline'>;
}
declare module 'markdown-it/lib/rules_inline/image.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/image'>;
}
declare module 'markdown-it/lib/rules_inline/link.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/link'>;
}
declare module 'markdown-it/lib/rules_inline/newline.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/newline'>;
}
declare module 'markdown-it/lib/rules_inline/state_inline.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/state_inline'>;
}
declare module 'markdown-it/lib/rules_inline/strikethrough.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/strikethrough'>;
}
declare module 'markdown-it/lib/rules_inline/text_collapse.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/text_collapse'>;
}
declare module 'markdown-it/lib/rules_inline/text.js' {
  declare module.exports: $Exports<'markdown-it/lib/rules_inline/text'>;
}
declare module 'markdown-it/lib/token.js' {
  declare module.exports: $Exports<'markdown-it/lib/token'>;
}
