// flow-typed signature: 59525f7f6d17528143c6a937dde99b53
// flow-typed version: <<STUB>>/mkdirp_v^0.5.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mkdirp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mkdirp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mkdirp/bin/cmd' {
  declare module.exports: any;
}

declare module 'mkdirp/examples/pow' {
  declare module.exports: any;
}

declare module 'mkdirp/test/chmod' {
  declare module.exports: any;
}

declare module 'mkdirp/test/clobber' {
  declare module.exports: any;
}

declare module 'mkdirp/test/mkdirp' {
  declare module.exports: any;
}

declare module 'mkdirp/test/opts_fs_sync' {
  declare module.exports: any;
}

declare module 'mkdirp/test/opts_fs' {
  declare module.exports: any;
}

declare module 'mkdirp/test/perm_sync' {
  declare module.exports: any;
}

declare module 'mkdirp/test/perm' {
  declare module.exports: any;
}

declare module 'mkdirp/test/race' {
  declare module.exports: any;
}

declare module 'mkdirp/test/rel' {
  declare module.exports: any;
}

declare module 'mkdirp/test/return_sync' {
  declare module.exports: any;
}

declare module 'mkdirp/test/return' {
  declare module.exports: any;
}

declare module 'mkdirp/test/root' {
  declare module.exports: any;
}

declare module 'mkdirp/test/sync' {
  declare module.exports: any;
}

declare module 'mkdirp/test/umask_sync' {
  declare module.exports: any;
}

declare module 'mkdirp/test/umask' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mkdirp/bin/cmd.js' {
  declare module.exports: $Exports<'mkdirp/bin/cmd'>;
}
declare module 'mkdirp/examples/pow.js' {
  declare module.exports: $Exports<'mkdirp/examples/pow'>;
}
declare module 'mkdirp/index' {
  declare module.exports: $Exports<'mkdirp'>;
}
declare module 'mkdirp/index.js' {
  declare module.exports: $Exports<'mkdirp'>;
}
declare module 'mkdirp/test/chmod.js' {
  declare module.exports: $Exports<'mkdirp/test/chmod'>;
}
declare module 'mkdirp/test/clobber.js' {
  declare module.exports: $Exports<'mkdirp/test/clobber'>;
}
declare module 'mkdirp/test/mkdirp.js' {
  declare module.exports: $Exports<'mkdirp/test/mkdirp'>;
}
declare module 'mkdirp/test/opts_fs_sync.js' {
  declare module.exports: $Exports<'mkdirp/test/opts_fs_sync'>;
}
declare module 'mkdirp/test/opts_fs.js' {
  declare module.exports: $Exports<'mkdirp/test/opts_fs'>;
}
declare module 'mkdirp/test/perm_sync.js' {
  declare module.exports: $Exports<'mkdirp/test/perm_sync'>;
}
declare module 'mkdirp/test/perm.js' {
  declare module.exports: $Exports<'mkdirp/test/perm'>;
}
declare module 'mkdirp/test/race.js' {
  declare module.exports: $Exports<'mkdirp/test/race'>;
}
declare module 'mkdirp/test/rel.js' {
  declare module.exports: $Exports<'mkdirp/test/rel'>;
}
declare module 'mkdirp/test/return_sync.js' {
  declare module.exports: $Exports<'mkdirp/test/return_sync'>;
}
declare module 'mkdirp/test/return.js' {
  declare module.exports: $Exports<'mkdirp/test/return'>;
}
declare module 'mkdirp/test/root.js' {
  declare module.exports: $Exports<'mkdirp/test/root'>;
}
declare module 'mkdirp/test/sync.js' {
  declare module.exports: $Exports<'mkdirp/test/sync'>;
}
declare module 'mkdirp/test/umask_sync.js' {
  declare module.exports: $Exports<'mkdirp/test/umask_sync'>;
}
declare module 'mkdirp/test/umask.js' {
  declare module.exports: $Exports<'mkdirp/test/umask'>;
}
