// flow-typed signature: 7fab76143c81e6d2baefea1420ced778
// flow-typed version: <<STUB>>/negotiator_v^0.6.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'negotiator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'negotiator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'negotiator/lib/charset' {
  declare module.exports: any;
}

declare module 'negotiator/lib/encoding' {
  declare module.exports: any;
}

declare module 'negotiator/lib/language' {
  declare module.exports: any;
}

declare module 'negotiator/lib/mediaType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'negotiator/index' {
  declare module.exports: $Exports<'negotiator'>;
}
declare module 'negotiator/index.js' {
  declare module.exports: $Exports<'negotiator'>;
}
declare module 'negotiator/lib/charset.js' {
  declare module.exports: $Exports<'negotiator/lib/charset'>;
}
declare module 'negotiator/lib/encoding.js' {
  declare module.exports: $Exports<'negotiator/lib/encoding'>;
}
declare module 'negotiator/lib/language.js' {
  declare module.exports: $Exports<'negotiator/lib/language'>;
}
declare module 'negotiator/lib/mediaType.js' {
  declare module.exports: $Exports<'negotiator/lib/mediaType'>;
}
