// flow-typed signature: 3105ff82577f437b2ac5d9b317152186
// flow-typed version: <<STUB>>/node-cjsx_v^2.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-cjsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-cjsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-cjsx/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-cjsx/index' {
  declare module.exports: $Exports<'node-cjsx'>;
}
declare module 'node-cjsx/index.js' {
  declare module.exports: $Exports<'node-cjsx'>;
}
declare module 'node-cjsx/register.js' {
  declare module.exports: $Exports<'node-cjsx/register'>;
}
