// flow-typed signature: 84310563880a6d344c86a6c200f70f05
// flow-typed version: <<STUB>>/nyc_v^7.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nyc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nyc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nyc/bin/nyc' {
  declare module.exports: any;
}

declare module 'nyc/bin/wrap' {
  declare module.exports: any;
}

declare module 'nyc/lib/commands/instrument' {
  declare module.exports: any;
}

declare module 'nyc/lib/instrumenters/istanbul' {
  declare module.exports: any;
}

declare module 'nyc/lib/instrumenters/noop' {
  declare module.exports: any;
}

declare module 'nyc/lib/process-args' {
  declare module.exports: any;
}

declare module 'nyc/lib/self-coverage-helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nyc/bin/nyc.js' {
  declare module.exports: $Exports<'nyc/bin/nyc'>;
}
declare module 'nyc/bin/wrap.js' {
  declare module.exports: $Exports<'nyc/bin/wrap'>;
}
declare module 'nyc/index' {
  declare module.exports: $Exports<'nyc'>;
}
declare module 'nyc/index.js' {
  declare module.exports: $Exports<'nyc'>;
}
declare module 'nyc/lib/commands/instrument.js' {
  declare module.exports: $Exports<'nyc/lib/commands/instrument'>;
}
declare module 'nyc/lib/instrumenters/istanbul.js' {
  declare module.exports: $Exports<'nyc/lib/instrumenters/istanbul'>;
}
declare module 'nyc/lib/instrumenters/noop.js' {
  declare module.exports: $Exports<'nyc/lib/instrumenters/noop'>;
}
declare module 'nyc/lib/process-args.js' {
  declare module.exports: $Exports<'nyc/lib/process-args'>;
}
declare module 'nyc/lib/self-coverage-helper.js' {
  declare module.exports: $Exports<'nyc/lib/self-coverage-helper'>;
}
