// flow-typed signature: 3485a540ad1e4b77448643b033c6b492
// flow-typed version: <<STUB>>/offline-plugin_v^3.4.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'offline-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'offline-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'offline-plugin/empty-entry' {
  declare module.exports: any;
}

declare module 'offline-plugin/lib/app-cache' {
  declare module.exports: any;
}

declare module 'offline-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'offline-plugin/lib/misc/runtime-loader' {
  declare module.exports: any;
}

declare module 'offline-plugin/lib/misc/sw-loader' {
  declare module.exports: any;
}

declare module 'offline-plugin/lib/misc/sw-polyfill' {
  declare module.exports: any;
}

declare module 'offline-plugin/lib/misc/sw-template' {
  declare module.exports: any;
}

declare module 'offline-plugin/lib/misc/utils' {
  declare module.exports: any;
}

declare module 'offline-plugin/lib/service-worker' {
  declare module.exports: any;
}

declare module 'offline-plugin/runtime' {
  declare module.exports: any;
}

declare module 'offline-plugin/tpls/runtime-template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'offline-plugin/empty-entry.js' {
  declare module.exports: $Exports<'offline-plugin/empty-entry'>;
}
declare module 'offline-plugin/lib/app-cache.js' {
  declare module.exports: $Exports<'offline-plugin/lib/app-cache'>;
}
declare module 'offline-plugin/lib/index.js' {
  declare module.exports: $Exports<'offline-plugin/lib/index'>;
}
declare module 'offline-plugin/lib/misc/runtime-loader.js' {
  declare module.exports: $Exports<'offline-plugin/lib/misc/runtime-loader'>;
}
declare module 'offline-plugin/lib/misc/sw-loader.js' {
  declare module.exports: $Exports<'offline-plugin/lib/misc/sw-loader'>;
}
declare module 'offline-plugin/lib/misc/sw-polyfill.js' {
  declare module.exports: $Exports<'offline-plugin/lib/misc/sw-polyfill'>;
}
declare module 'offline-plugin/lib/misc/sw-template.js' {
  declare module.exports: $Exports<'offline-plugin/lib/misc/sw-template'>;
}
declare module 'offline-plugin/lib/misc/utils.js' {
  declare module.exports: $Exports<'offline-plugin/lib/misc/utils'>;
}
declare module 'offline-plugin/lib/service-worker.js' {
  declare module.exports: $Exports<'offline-plugin/lib/service-worker'>;
}
declare module 'offline-plugin/runtime.js' {
  declare module.exports: $Exports<'offline-plugin/runtime'>;
}
declare module 'offline-plugin/tpls/runtime-template.js' {
  declare module.exports: $Exports<'offline-plugin/tpls/runtime-template'>;
}
