// flow-typed signature: 2b872c0c2dc2751a5cc4620ec81f2a74
// flow-typed version: <<STUB>>/postcss-reporter_v^1.4.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-reporter/lib/formatter' {
  declare module.exports: any;
}

declare module 'postcss-reporter/lib/reporter' {
  declare module.exports: any;
}

declare module 'postcss-reporter/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-reporter/index' {
  declare module.exports: $Exports<'postcss-reporter'>;
}
declare module 'postcss-reporter/index.js' {
  declare module.exports: $Exports<'postcss-reporter'>;
}
declare module 'postcss-reporter/lib/formatter.js' {
  declare module.exports: $Exports<'postcss-reporter/lib/formatter'>;
}
declare module 'postcss-reporter/lib/reporter.js' {
  declare module.exports: $Exports<'postcss-reporter/lib/reporter'>;
}
declare module 'postcss-reporter/lib/util.js' {
  declare module.exports: $Exports<'postcss-reporter/lib/util'>;
}
