// flow-typed signature: 8ee5a17f2f846e09a0633b8366abea46
// flow-typed version: <<STUB>>/react-router_v^2.8.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/es6/applyRouterMiddleware' {
  declare module.exports: any;
}

declare module 'react-router/es6/AsyncUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/browserHistory' {
  declare module.exports: any;
}

declare module 'react-router/es6/computeChangedRoutes' {
  declare module.exports: any;
}

declare module 'react-router/es6/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'react-router/es6/createRouterHistory' {
  declare module.exports: any;
}

declare module 'react-router/es6/createTransitionManager' {
  declare module.exports: any;
}

declare module 'react-router/es6/deprecateObjectProperties' {
  declare module.exports: any;
}

declare module 'react-router/es6/getComponents' {
  declare module.exports: any;
}

declare module 'react-router/es6/getRouteParams' {
  declare module.exports: any;
}

declare module 'react-router/es6/hashHistory' {
  declare module.exports: any;
}

declare module 'react-router/es6/History' {
  declare module.exports: any;
}

declare module 'react-router/es6/index' {
  declare module.exports: any;
}

declare module 'react-router/es6/IndexLink' {
  declare module.exports: any;
}

declare module 'react-router/es6/IndexRedirect' {
  declare module.exports: any;
}

declare module 'react-router/es6/IndexRoute' {
  declare module.exports: any;
}

declare module 'react-router/es6/InternalPropTypes' {
  declare module.exports: any;
}

declare module 'react-router/es6/isActive' {
  declare module.exports: any;
}

declare module 'react-router/es6/Lifecycle' {
  declare module.exports: any;
}

declare module 'react-router/es6/Link' {
  declare module.exports: any;
}

declare module 'react-router/es6/makeStateWithLocation' {
  declare module.exports: any;
}

declare module 'react-router/es6/match' {
  declare module.exports: any;
}

declare module 'react-router/es6/matchRoutes' {
  declare module.exports: any;
}

declare module 'react-router/es6/PatternUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/PropTypes' {
  declare module.exports: any;
}

declare module 'react-router/es6/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/es6/Route' {
  declare module.exports: any;
}

declare module 'react-router/es6/RouteContext' {
  declare module.exports: any;
}

declare module 'react-router/es6/Router' {
  declare module.exports: any;
}

declare module 'react-router/es6/RouterContext' {
  declare module.exports: any;
}

declare module 'react-router/es6/RouterUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/routerWarning' {
  declare module.exports: any;
}

declare module 'react-router/es6/RouteUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/RoutingContext' {
  declare module.exports: any;
}

declare module 'react-router/es6/TransitionUtils' {
  declare module.exports: any;
}

declare module 'react-router/es6/useRouterHistory' {
  declare module.exports: any;
}

declare module 'react-router/es6/useRoutes' {
  declare module.exports: any;
}

declare module 'react-router/es6/withRouter' {
  declare module.exports: any;
}

declare module 'react-router/lib/applyRouterMiddleware' {
  declare module.exports: any;
}

declare module 'react-router/lib/AsyncUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/browserHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/computeChangedRoutes' {
  declare module.exports: any;
}

declare module 'react-router/lib/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/createRouterHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/createTransitionManager' {
  declare module.exports: any;
}

declare module 'react-router/lib/deprecateObjectProperties' {
  declare module.exports: any;
}

declare module 'react-router/lib/getComponents' {
  declare module.exports: any;
}

declare module 'react-router/lib/getRouteParams' {
  declare module.exports: any;
}

declare module 'react-router/lib/hashHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/History' {
  declare module.exports: any;
}

declare module 'react-router/lib/index' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexLink' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexRedirect' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexRoute' {
  declare module.exports: any;
}

declare module 'react-router/lib/InternalPropTypes' {
  declare module.exports: any;
}

declare module 'react-router/lib/isActive' {
  declare module.exports: any;
}

declare module 'react-router/lib/Lifecycle' {
  declare module.exports: any;
}

declare module 'react-router/lib/Link' {
  declare module.exports: any;
}

declare module 'react-router/lib/makeStateWithLocation' {
  declare module.exports: any;
}

declare module 'react-router/lib/match' {
  declare module.exports: any;
}

declare module 'react-router/lib/matchRoutes' {
  declare module.exports: any;
}

declare module 'react-router/lib/PatternUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/PropTypes' {
  declare module.exports: any;
}

declare module 'react-router/lib/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/lib/Route' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouteContext' {
  declare module.exports: any;
}

declare module 'react-router/lib/Router' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouterContext' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouterUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/routerWarning' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouteUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/RoutingContext' {
  declare module.exports: any;
}

declare module 'react-router/lib/TransitionUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/useRouterHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/useRoutes' {
  declare module.exports: any;
}

declare module 'react-router/lib/withRouter' {
  declare module.exports: any;
}

declare module 'react-router/umd/ReactRouter' {
  declare module.exports: any;
}

declare module 'react-router/umd/ReactRouter.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/es6/applyRouterMiddleware.js' {
  declare module.exports: $Exports<'react-router/es6/applyRouterMiddleware'>;
}
declare module 'react-router/es6/AsyncUtils.js' {
  declare module.exports: $Exports<'react-router/es6/AsyncUtils'>;
}
declare module 'react-router/es6/browserHistory.js' {
  declare module.exports: $Exports<'react-router/es6/browserHistory'>;
}
declare module 'react-router/es6/computeChangedRoutes.js' {
  declare module.exports: $Exports<'react-router/es6/computeChangedRoutes'>;
}
declare module 'react-router/es6/createMemoryHistory.js' {
  declare module.exports: $Exports<'react-router/es6/createMemoryHistory'>;
}
declare module 'react-router/es6/createRouterHistory.js' {
  declare module.exports: $Exports<'react-router/es6/createRouterHistory'>;
}
declare module 'react-router/es6/createTransitionManager.js' {
  declare module.exports: $Exports<'react-router/es6/createTransitionManager'>;
}
declare module 'react-router/es6/deprecateObjectProperties.js' {
  declare module.exports: $Exports<'react-router/es6/deprecateObjectProperties'>;
}
declare module 'react-router/es6/getComponents.js' {
  declare module.exports: $Exports<'react-router/es6/getComponents'>;
}
declare module 'react-router/es6/getRouteParams.js' {
  declare module.exports: $Exports<'react-router/es6/getRouteParams'>;
}
declare module 'react-router/es6/hashHistory.js' {
  declare module.exports: $Exports<'react-router/es6/hashHistory'>;
}
declare module 'react-router/es6/History.js' {
  declare module.exports: $Exports<'react-router/es6/History'>;
}
declare module 'react-router/es6/index.js' {
  declare module.exports: $Exports<'react-router/es6/index'>;
}
declare module 'react-router/es6/IndexLink.js' {
  declare module.exports: $Exports<'react-router/es6/IndexLink'>;
}
declare module 'react-router/es6/IndexRedirect.js' {
  declare module.exports: $Exports<'react-router/es6/IndexRedirect'>;
}
declare module 'react-router/es6/IndexRoute.js' {
  declare module.exports: $Exports<'react-router/es6/IndexRoute'>;
}
declare module 'react-router/es6/InternalPropTypes.js' {
  declare module.exports: $Exports<'react-router/es6/InternalPropTypes'>;
}
declare module 'react-router/es6/isActive.js' {
  declare module.exports: $Exports<'react-router/es6/isActive'>;
}
declare module 'react-router/es6/Lifecycle.js' {
  declare module.exports: $Exports<'react-router/es6/Lifecycle'>;
}
declare module 'react-router/es6/Link.js' {
  declare module.exports: $Exports<'react-router/es6/Link'>;
}
declare module 'react-router/es6/makeStateWithLocation.js' {
  declare module.exports: $Exports<'react-router/es6/makeStateWithLocation'>;
}
declare module 'react-router/es6/match.js' {
  declare module.exports: $Exports<'react-router/es6/match'>;
}
declare module 'react-router/es6/matchRoutes.js' {
  declare module.exports: $Exports<'react-router/es6/matchRoutes'>;
}
declare module 'react-router/es6/PatternUtils.js' {
  declare module.exports: $Exports<'react-router/es6/PatternUtils'>;
}
declare module 'react-router/es6/PropTypes.js' {
  declare module.exports: $Exports<'react-router/es6/PropTypes'>;
}
declare module 'react-router/es6/Redirect.js' {
  declare module.exports: $Exports<'react-router/es6/Redirect'>;
}
declare module 'react-router/es6/Route.js' {
  declare module.exports: $Exports<'react-router/es6/Route'>;
}
declare module 'react-router/es6/RouteContext.js' {
  declare module.exports: $Exports<'react-router/es6/RouteContext'>;
}
declare module 'react-router/es6/Router.js' {
  declare module.exports: $Exports<'react-router/es6/Router'>;
}
declare module 'react-router/es6/RouterContext.js' {
  declare module.exports: $Exports<'react-router/es6/RouterContext'>;
}
declare module 'react-router/es6/RouterUtils.js' {
  declare module.exports: $Exports<'react-router/es6/RouterUtils'>;
}
declare module 'react-router/es6/routerWarning.js' {
  declare module.exports: $Exports<'react-router/es6/routerWarning'>;
}
declare module 'react-router/es6/RouteUtils.js' {
  declare module.exports: $Exports<'react-router/es6/RouteUtils'>;
}
declare module 'react-router/es6/RoutingContext.js' {
  declare module.exports: $Exports<'react-router/es6/RoutingContext'>;
}
declare module 'react-router/es6/TransitionUtils.js' {
  declare module.exports: $Exports<'react-router/es6/TransitionUtils'>;
}
declare module 'react-router/es6/useRouterHistory.js' {
  declare module.exports: $Exports<'react-router/es6/useRouterHistory'>;
}
declare module 'react-router/es6/useRoutes.js' {
  declare module.exports: $Exports<'react-router/es6/useRoutes'>;
}
declare module 'react-router/es6/withRouter.js' {
  declare module.exports: $Exports<'react-router/es6/withRouter'>;
}
declare module 'react-router/lib/applyRouterMiddleware.js' {
  declare module.exports: $Exports<'react-router/lib/applyRouterMiddleware'>;
}
declare module 'react-router/lib/AsyncUtils.js' {
  declare module.exports: $Exports<'react-router/lib/AsyncUtils'>;
}
declare module 'react-router/lib/browserHistory.js' {
  declare module.exports: $Exports<'react-router/lib/browserHistory'>;
}
declare module 'react-router/lib/computeChangedRoutes.js' {
  declare module.exports: $Exports<'react-router/lib/computeChangedRoutes'>;
}
declare module 'react-router/lib/createMemoryHistory.js' {
  declare module.exports: $Exports<'react-router/lib/createMemoryHistory'>;
}
declare module 'react-router/lib/createRouterHistory.js' {
  declare module.exports: $Exports<'react-router/lib/createRouterHistory'>;
}
declare module 'react-router/lib/createTransitionManager.js' {
  declare module.exports: $Exports<'react-router/lib/createTransitionManager'>;
}
declare module 'react-router/lib/deprecateObjectProperties.js' {
  declare module.exports: $Exports<'react-router/lib/deprecateObjectProperties'>;
}
declare module 'react-router/lib/getComponents.js' {
  declare module.exports: $Exports<'react-router/lib/getComponents'>;
}
declare module 'react-router/lib/getRouteParams.js' {
  declare module.exports: $Exports<'react-router/lib/getRouteParams'>;
}
declare module 'react-router/lib/hashHistory.js' {
  declare module.exports: $Exports<'react-router/lib/hashHistory'>;
}
declare module 'react-router/lib/History.js' {
  declare module.exports: $Exports<'react-router/lib/History'>;
}
declare module 'react-router/lib/index.js' {
  declare module.exports: $Exports<'react-router/lib/index'>;
}
declare module 'react-router/lib/IndexLink.js' {
  declare module.exports: $Exports<'react-router/lib/IndexLink'>;
}
declare module 'react-router/lib/IndexRedirect.js' {
  declare module.exports: $Exports<'react-router/lib/IndexRedirect'>;
}
declare module 'react-router/lib/IndexRoute.js' {
  declare module.exports: $Exports<'react-router/lib/IndexRoute'>;
}
declare module 'react-router/lib/InternalPropTypes.js' {
  declare module.exports: $Exports<'react-router/lib/InternalPropTypes'>;
}
declare module 'react-router/lib/isActive.js' {
  declare module.exports: $Exports<'react-router/lib/isActive'>;
}
declare module 'react-router/lib/Lifecycle.js' {
  declare module.exports: $Exports<'react-router/lib/Lifecycle'>;
}
declare module 'react-router/lib/Link.js' {
  declare module.exports: $Exports<'react-router/lib/Link'>;
}
declare module 'react-router/lib/makeStateWithLocation.js' {
  declare module.exports: $Exports<'react-router/lib/makeStateWithLocation'>;
}
declare module 'react-router/lib/match.js' {
  declare module.exports: $Exports<'react-router/lib/match'>;
}
declare module 'react-router/lib/matchRoutes.js' {
  declare module.exports: $Exports<'react-router/lib/matchRoutes'>;
}
declare module 'react-router/lib/PatternUtils.js' {
  declare module.exports: $Exports<'react-router/lib/PatternUtils'>;
}
declare module 'react-router/lib/PropTypes.js' {
  declare module.exports: $Exports<'react-router/lib/PropTypes'>;
}
declare module 'react-router/lib/Redirect.js' {
  declare module.exports: $Exports<'react-router/lib/Redirect'>;
}
declare module 'react-router/lib/Route.js' {
  declare module.exports: $Exports<'react-router/lib/Route'>;
}
declare module 'react-router/lib/RouteContext.js' {
  declare module.exports: $Exports<'react-router/lib/RouteContext'>;
}
declare module 'react-router/lib/Router.js' {
  declare module.exports: $Exports<'react-router/lib/Router'>;
}
declare module 'react-router/lib/RouterContext.js' {
  declare module.exports: $Exports<'react-router/lib/RouterContext'>;
}
declare module 'react-router/lib/RouterUtils.js' {
  declare module.exports: $Exports<'react-router/lib/RouterUtils'>;
}
declare module 'react-router/lib/routerWarning.js' {
  declare module.exports: $Exports<'react-router/lib/routerWarning'>;
}
declare module 'react-router/lib/RouteUtils.js' {
  declare module.exports: $Exports<'react-router/lib/RouteUtils'>;
}
declare module 'react-router/lib/RoutingContext.js' {
  declare module.exports: $Exports<'react-router/lib/RoutingContext'>;
}
declare module 'react-router/lib/TransitionUtils.js' {
  declare module.exports: $Exports<'react-router/lib/TransitionUtils'>;
}
declare module 'react-router/lib/useRouterHistory.js' {
  declare module.exports: $Exports<'react-router/lib/useRouterHistory'>;
}
declare module 'react-router/lib/useRoutes.js' {
  declare module.exports: $Exports<'react-router/lib/useRoutes'>;
}
declare module 'react-router/lib/withRouter.js' {
  declare module.exports: $Exports<'react-router/lib/withRouter'>;
}
declare module 'react-router/umd/ReactRouter.js' {
  declare module.exports: $Exports<'react-router/umd/ReactRouter'>;
}
declare module 'react-router/umd/ReactRouter.min.js' {
  declare module.exports: $Exports<'react-router/umd/ReactRouter.min'>;
}
