// flow-typed signature: 58b2920602801b95c14feb01cd7a1aa5
// flow-typed version: <<STUB>>/style-loader_v^0.13.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-loader/addStyles' {
  declare module.exports: any;
}

declare module 'style-loader/addStyleUrl' {
  declare module.exports: any;
}

declare module 'style-loader/url' {
  declare module.exports: any;
}

declare module 'style-loader/useable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-loader/addStyles.js' {
  declare module.exports: $Exports<'style-loader/addStyles'>;
}
declare module 'style-loader/addStyleUrl.js' {
  declare module.exports: $Exports<'style-loader/addStyleUrl'>;
}
declare module 'style-loader/index' {
  declare module.exports: $Exports<'style-loader'>;
}
declare module 'style-loader/index.js' {
  declare module.exports: $Exports<'style-loader'>;
}
declare module 'style-loader/url.js' {
  declare module.exports: $Exports<'style-loader/url'>;
}
declare module 'style-loader/useable.js' {
  declare module.exports: $Exports<'style-loader/useable'>;
}
