// flow-typed signature: eb995e377041958d23de8e6fe5360006
// flow-typed version: <<STUB>>/tracer_v^0.8.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tracer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tracer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tracer/example/colorConsole' {
  declare module.exports: any;
}

declare module 'tracer/example/colorConsole2' {
  declare module.exports: any;
}

declare module 'tracer/example/config' {
  declare module.exports: any;
}

declare module 'tracer/example/console' {
  declare module.exports: any;
}

declare module 'tracer/example/dailyfile' {
  declare module.exports: any;
}

declare module 'tracer/example/depth' {
  declare module.exports: any;
}

declare module 'tracer/example/express/app' {
  declare module.exports: any;
}

declare module 'tracer/example/express/config' {
  declare module.exports: any;
}

declare module 'tracer/example/express/routes/index' {
  declare module.exports: any;
}

declare module 'tracer/example/file' {
  declare module.exports: any;
}

declare module 'tracer/example/filter' {
  declare module.exports: any;
}

declare module 'tracer/example/format' {
  declare module.exports: any;
}

declare module 'tracer/example/format2' {
  declare module.exports: any;
}

declare module 'tracer/example/format3' {
  declare module.exports: any;
}

declare module 'tracer/example/format4' {
  declare module.exports: any;
}

declare module 'tracer/example/hourlog' {
  declare module.exports: any;
}

declare module 'tracer/example/level' {
  declare module.exports: any;
}

declare module 'tracer/example/methods' {
  declare module.exports: any;
}

declare module 'tracer/example/mongodb' {
  declare module.exports: any;
}

declare module 'tracer/example/multipleTransport' {
  declare module.exports: any;
}

declare module 'tracer/example/setLevel' {
  declare module.exports: any;
}

declare module 'tracer/example/setLevelAnother' {
  declare module.exports: any;
}

declare module 'tracer/example/stream' {
  declare module.exports: any;
}

declare module 'tracer/example/stress' {
  declare module.exports: any;
}

declare module 'tracer/example/test' {
  declare module.exports: any;
}

declare module 'tracer/lib/color_console' {
  declare module.exports: any;
}

declare module 'tracer/lib/console' {
  declare module.exports: any;
}

declare module 'tracer/lib/dailyfile' {
  declare module.exports: any;
}

declare module 'tracer/lib/index' {
  declare module.exports: any;
}

declare module 'tracer/lib/settings' {
  declare module.exports: any;
}

declare module 'tracer/lib/utils' {
  declare module.exports: any;
}

declare module 'tracer/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tracer/example/colorConsole.js' {
  declare module.exports: $Exports<'tracer/example/colorConsole'>;
}
declare module 'tracer/example/colorConsole2.js' {
  declare module.exports: $Exports<'tracer/example/colorConsole2'>;
}
declare module 'tracer/example/config.js' {
  declare module.exports: $Exports<'tracer/example/config'>;
}
declare module 'tracer/example/console.js' {
  declare module.exports: $Exports<'tracer/example/console'>;
}
declare module 'tracer/example/dailyfile.js' {
  declare module.exports: $Exports<'tracer/example/dailyfile'>;
}
declare module 'tracer/example/depth.js' {
  declare module.exports: $Exports<'tracer/example/depth'>;
}
declare module 'tracer/example/express/app.js' {
  declare module.exports: $Exports<'tracer/example/express/app'>;
}
declare module 'tracer/example/express/config.js' {
  declare module.exports: $Exports<'tracer/example/express/config'>;
}
declare module 'tracer/example/express/routes/index.js' {
  declare module.exports: $Exports<'tracer/example/express/routes/index'>;
}
declare module 'tracer/example/file.js' {
  declare module.exports: $Exports<'tracer/example/file'>;
}
declare module 'tracer/example/filter.js' {
  declare module.exports: $Exports<'tracer/example/filter'>;
}
declare module 'tracer/example/format.js' {
  declare module.exports: $Exports<'tracer/example/format'>;
}
declare module 'tracer/example/format2.js' {
  declare module.exports: $Exports<'tracer/example/format2'>;
}
declare module 'tracer/example/format3.js' {
  declare module.exports: $Exports<'tracer/example/format3'>;
}
declare module 'tracer/example/format4.js' {
  declare module.exports: $Exports<'tracer/example/format4'>;
}
declare module 'tracer/example/hourlog.js' {
  declare module.exports: $Exports<'tracer/example/hourlog'>;
}
declare module 'tracer/example/level.js' {
  declare module.exports: $Exports<'tracer/example/level'>;
}
declare module 'tracer/example/methods.js' {
  declare module.exports: $Exports<'tracer/example/methods'>;
}
declare module 'tracer/example/mongodb.js' {
  declare module.exports: $Exports<'tracer/example/mongodb'>;
}
declare module 'tracer/example/multipleTransport.js' {
  declare module.exports: $Exports<'tracer/example/multipleTransport'>;
}
declare module 'tracer/example/setLevel.js' {
  declare module.exports: $Exports<'tracer/example/setLevel'>;
}
declare module 'tracer/example/setLevelAnother.js' {
  declare module.exports: $Exports<'tracer/example/setLevelAnother'>;
}
declare module 'tracer/example/stream.js' {
  declare module.exports: $Exports<'tracer/example/stream'>;
}
declare module 'tracer/example/stress.js' {
  declare module.exports: $Exports<'tracer/example/stress'>;
}
declare module 'tracer/example/test.js' {
  declare module.exports: $Exports<'tracer/example/test'>;
}
declare module 'tracer/index' {
  declare module.exports: $Exports<'tracer'>;
}
declare module 'tracer/index.js' {
  declare module.exports: $Exports<'tracer'>;
}
declare module 'tracer/lib/color_console.js' {
  declare module.exports: $Exports<'tracer/lib/color_console'>;
}
declare module 'tracer/lib/console.js' {
  declare module.exports: $Exports<'tracer/lib/console'>;
}
declare module 'tracer/lib/dailyfile.js' {
  declare module.exports: $Exports<'tracer/lib/dailyfile'>;
}
declare module 'tracer/lib/index.js' {
  declare module.exports: $Exports<'tracer/lib/index'>;
}
declare module 'tracer/lib/settings.js' {
  declare module.exports: $Exports<'tracer/lib/settings'>;
}
declare module 'tracer/lib/utils.js' {
  declare module.exports: $Exports<'tracer/lib/utils'>;
}
declare module 'tracer/test/test.js' {
  declare module.exports: $Exports<'tracer/test/test'>;
}
