// flow-typed signature: b66211ee6c714558fb7f8471a64578ca
// flow-typed version: <<STUB>>/unist-util-select_v^1.5.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unist-util-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'unist-util-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unist-util-select/lib/ast-walkers' {
  declare module.exports: any;
}

declare module 'unist-util-select/lib/collector' {
  declare module.exports: any;
}

declare module 'unist-util-select/lib/match-node' {
  declare module.exports: any;
}

declare module 'unist-util-select/lib/select' {
  declare module.exports: any;
}

declare module 'unist-util-select/lib/selector' {
  declare module.exports: any;
}

declare module 'unist-util-select/lib/type-index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unist-util-select/index' {
  declare module.exports: $Exports<'unist-util-select'>;
}
declare module 'unist-util-select/index.js' {
  declare module.exports: $Exports<'unist-util-select'>;
}
declare module 'unist-util-select/lib/ast-walkers.js' {
  declare module.exports: $Exports<'unist-util-select/lib/ast-walkers'>;
}
declare module 'unist-util-select/lib/collector.js' {
  declare module.exports: $Exports<'unist-util-select/lib/collector'>;
}
declare module 'unist-util-select/lib/match-node.js' {
  declare module.exports: $Exports<'unist-util-select/lib/match-node'>;
}
declare module 'unist-util-select/lib/select.js' {
  declare module.exports: $Exports<'unist-util-select/lib/select'>;
}
declare module 'unist-util-select/lib/selector.js' {
  declare module.exports: $Exports<'unist-util-select/lib/selector'>;
}
declare module 'unist-util-select/lib/type-index.js' {
  declare module.exports: $Exports<'unist-util-select/lib/type-index'>;
}
