// flow-typed signature: 909cb4e99c924772aecfe622e856bee0
// flow-typed version: <<STUB>>/webpack-require_v0.0.16/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-require/lib/sourceMapSupport' {
  declare module.exports: any;
}

declare module 'webpack-require/lib/webpackRequire' {
  declare module.exports: any;
}

declare module 'webpack-require/lib/webpackRequireEntrypoint' {
  declare module.exports: any;
}

declare module 'webpack-require/spec/app/build/bundle' {
  declare module.exports: any;
}

declare module 'webpack-require/spec/app/component' {
  declare module.exports: any;
}

declare module 'webpack-require/spec/app/entrypoint' {
  declare module.exports: any;
}

declare module 'webpack-require/spec/app/stateful' {
  declare module.exports: any;
}

declare module 'webpack-require/spec/app/throwError' {
  declare module.exports: any;
}

declare module 'webpack-require/spec/app/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-require/spec/webpackRequire.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-require/lib/sourceMapSupport.js' {
  declare module.exports: $Exports<'webpack-require/lib/sourceMapSupport'>;
}
declare module 'webpack-require/lib/webpackRequire.js' {
  declare module.exports: $Exports<'webpack-require/lib/webpackRequire'>;
}
declare module 'webpack-require/lib/webpackRequireEntrypoint.js' {
  declare module.exports: $Exports<'webpack-require/lib/webpackRequireEntrypoint'>;
}
declare module 'webpack-require/spec/app/build/bundle.js' {
  declare module.exports: $Exports<'webpack-require/spec/app/build/bundle'>;
}
declare module 'webpack-require/spec/app/component.js' {
  declare module.exports: $Exports<'webpack-require/spec/app/component'>;
}
declare module 'webpack-require/spec/app/entrypoint.js' {
  declare module.exports: $Exports<'webpack-require/spec/app/entrypoint'>;
}
declare module 'webpack-require/spec/app/stateful.js' {
  declare module.exports: $Exports<'webpack-require/spec/app/stateful'>;
}
declare module 'webpack-require/spec/app/throwError.js' {
  declare module.exports: $Exports<'webpack-require/spec/app/throwError'>;
}
declare module 'webpack-require/spec/app/webpack.config.js' {
  declare module.exports: $Exports<'webpack-require/spec/app/webpack.config'>;
}
declare module 'webpack-require/spec/webpackRequire.spec.js' {
  declare module.exports: $Exports<'webpack-require/spec/webpackRequire.spec'>;
}
