// flow-typed signature: 9fa03d2b3b83d8af3f5327d9f4a4bcc7
// flow-typed version: <<STUB>>/webpack-md5-hash_v0.0.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-md5-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-md5-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-md5-hash/build' {
  declare module.exports: any;
}

declare module 'webpack-md5-hash/example/js/app' {
  declare module.exports: any;
}

declare module 'webpack-md5-hash/example/js/module' {
  declare module.exports: any;
}

declare module 'webpack-md5-hash/example/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-md5-hash/plugin/webpack_md5_hash' {
  declare module.exports: any;
}

declare module 'webpack-md5-hash/spec/fixtures/entry' {
  declare module.exports: any;
}

declare module 'webpack-md5-hash/spec/fixtures/module1' {
  declare module.exports: any;
}

declare module 'webpack-md5-hash/spec/fixtures/module2' {
  declare module.exports: any;
}

declare module 'webpack-md5-hash/spec/WebpackMD5Spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-md5-hash/build.js' {
  declare module.exports: $Exports<'webpack-md5-hash/build'>;
}
declare module 'webpack-md5-hash/example/js/app.js' {
  declare module.exports: $Exports<'webpack-md5-hash/example/js/app'>;
}
declare module 'webpack-md5-hash/example/js/module.js' {
  declare module.exports: $Exports<'webpack-md5-hash/example/js/module'>;
}
declare module 'webpack-md5-hash/example/webpack.config.js' {
  declare module.exports: $Exports<'webpack-md5-hash/example/webpack.config'>;
}
declare module 'webpack-md5-hash/index' {
  declare module.exports: $Exports<'webpack-md5-hash'>;
}
declare module 'webpack-md5-hash/index.js' {
  declare module.exports: $Exports<'webpack-md5-hash'>;
}
declare module 'webpack-md5-hash/plugin/webpack_md5_hash.js' {
  declare module.exports: $Exports<'webpack-md5-hash/plugin/webpack_md5_hash'>;
}
declare module 'webpack-md5-hash/spec/fixtures/entry.js' {
  declare module.exports: $Exports<'webpack-md5-hash/spec/fixtures/entry'>;
}
declare module 'webpack-md5-hash/spec/fixtures/module1.js' {
  declare module.exports: $Exports<'webpack-md5-hash/spec/fixtures/module1'>;
}
declare module 'webpack-md5-hash/spec/fixtures/module2.js' {
  declare module.exports: $Exports<'webpack-md5-hash/spec/fixtures/module2'>;
}
declare module 'webpack-md5-hash/spec/WebpackMD5Spec.js' {
  declare module.exports: $Exports<'webpack-md5-hash/spec/WebpackMD5Spec'>;
}
