// flow-typed signature: 14cf7e2fda81cfeaac3a05da7912c79c
// flow-typed version: <<STUB>>/webpack-dev-server_v^1.16.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-server/bin/webpack-dev-server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/index.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/index' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/live.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/live' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/socket' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/web_modules/jquery/index' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/web_modules/jquery/jquery-1.8.1' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/Server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-server/bin/webpack-dev-server.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/webpack-dev-server'>;
}
declare module 'webpack-dev-server/client/index.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/index.bundle'>;
}
declare module 'webpack-dev-server/client/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/index'>;
}
declare module 'webpack-dev-server/client/live.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/live.bundle'>;
}
declare module 'webpack-dev-server/client/live.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/live'>;
}
declare module 'webpack-dev-server/client/socket.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/socket'>;
}
declare module 'webpack-dev-server/client/web_modules/jquery/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/web_modules/jquery/index'>;
}
declare module 'webpack-dev-server/client/web_modules/jquery/jquery-1.8.1.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/web_modules/jquery/jquery-1.8.1'>;
}
declare module 'webpack-dev-server/client/webpack.config.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/webpack.config'>;
}
declare module 'webpack-dev-server/lib/Server.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/Server'>;
}
