// flow-typed signature: 5bf17bdf0e9b23569e126193430b210b
// flow-typed version: <<STUB>>/yaml-js_v^0.1.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yaml-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'yaml-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yaml-js/lib/composer' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/constructor' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/dumper' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/emitter' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/errors' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/events' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/loader' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/nodes' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/parser' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/reader' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/representer' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/resolver' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/scanner' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/serializer' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/tokens' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/util' {
  declare module.exports: any;
}

declare module 'yaml-js/lib/yaml' {
  declare module.exports: any;
}

declare module 'yaml-js/test/yaml-spec/platform/javascript' {
  declare module.exports: any;
}

declare module 'yaml-js/yaml' {
  declare module.exports: any;
}

declare module 'yaml-js/yaml.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yaml-js/lib/composer.js' {
  declare module.exports: $Exports<'yaml-js/lib/composer'>;
}
declare module 'yaml-js/lib/constructor.js' {
  declare module.exports: $Exports<'yaml-js/lib/constructor'>;
}
declare module 'yaml-js/lib/dumper.js' {
  declare module.exports: $Exports<'yaml-js/lib/dumper'>;
}
declare module 'yaml-js/lib/emitter.js' {
  declare module.exports: $Exports<'yaml-js/lib/emitter'>;
}
declare module 'yaml-js/lib/errors.js' {
  declare module.exports: $Exports<'yaml-js/lib/errors'>;
}
declare module 'yaml-js/lib/events.js' {
  declare module.exports: $Exports<'yaml-js/lib/events'>;
}
declare module 'yaml-js/lib/loader.js' {
  declare module.exports: $Exports<'yaml-js/lib/loader'>;
}
declare module 'yaml-js/lib/nodes.js' {
  declare module.exports: $Exports<'yaml-js/lib/nodes'>;
}
declare module 'yaml-js/lib/parser.js' {
  declare module.exports: $Exports<'yaml-js/lib/parser'>;
}
declare module 'yaml-js/lib/reader.js' {
  declare module.exports: $Exports<'yaml-js/lib/reader'>;
}
declare module 'yaml-js/lib/representer.js' {
  declare module.exports: $Exports<'yaml-js/lib/representer'>;
}
declare module 'yaml-js/lib/resolver.js' {
  declare module.exports: $Exports<'yaml-js/lib/resolver'>;
}
declare module 'yaml-js/lib/scanner.js' {
  declare module.exports: $Exports<'yaml-js/lib/scanner'>;
}
declare module 'yaml-js/lib/serializer.js' {
  declare module.exports: $Exports<'yaml-js/lib/serializer'>;
}
declare module 'yaml-js/lib/tokens.js' {
  declare module.exports: $Exports<'yaml-js/lib/tokens'>;
}
declare module 'yaml-js/lib/util.js' {
  declare module.exports: $Exports<'yaml-js/lib/util'>;
}
declare module 'yaml-js/lib/yaml.js' {
  declare module.exports: $Exports<'yaml-js/lib/yaml'>;
}
declare module 'yaml-js/test/yaml-spec/platform/javascript.js' {
  declare module.exports: $Exports<'yaml-js/test/yaml-spec/platform/javascript'>;
}
declare module 'yaml-js/yaml.js' {
  declare module.exports: $Exports<'yaml-js/yaml'>;
}
declare module 'yaml-js/yaml.min.js' {
  declare module.exports: $Exports<'yaml-js/yaml.min'>;
}
