import { fetch, Response } from 'node-fetch';
const usedReference = 'my cool ref';
const unusedReference = 'I hope to be removed';
export default function () {
  const x = new Response({});
  anotherSelfReferencedOne();
  return usedReference;
}

// such a structure is being generated by regenerator-runtime
function renderPage() {
  renderPage = () => {};
}
function anotherSelfReferencedOne() {
  anotherSelfReferencedOne = () => {};
}
