name: Documentation
description: Did you find an error in our documentation? Report your findings here.
labels: ["type: documentation"]
body:
  - type: markdown
    attributes:
      value: |
        # Welcome 👋

        Thanks for taking the time to fill out this issue.
        Please fill out each section below. This info allows Gatsby maintainers to triage and fix your issue as quickly as possible.

        Useful links:

        - Documentation: https://www.gatsbyjs.com/docs/
        - Contributing: https://www.gatsbyjs.com/contributing/
  - type: checkboxes
    attributes:
      label: Preliminary Checks
      description: Please make sure that you verify each checkbox and follow the instructions for them.
      options:
        - label: "This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues"
          required: true
        - label: "This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions"
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: |
        What problem(s) did you run into that caused you to request a fix to the documentation or additional documentation? What questions do you think we should answer?
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to Resolve this Issue
      description: How can the problem be solved? Are there any additional steps required? Do any other pages need to be updated?
      value: |
        1.
        2.
        3.
        ...
