import fs from "fs"
import pify from "pify"

export const writeFile = pify(fs.writeFile)

export const runQuery = (handler, query) =>
  handler(query).then(r => {
    if (r.errors) {
      throw new Error(r.errors.join(`, `))
    }

    return r.data
  })

export const defaultOptions = {
  // Override if you want to manually specify the RSS "generator" tag.
  generator: `GatsbyJS`,

  // Run a default query to gather some information about the site.
  query: `
    {
      site {
        siteMetadata {
          title
          description
          site_url
        }
      }
    }
  `,

  // Setup a few RSS object, merging on various feed-speciupfic options.
  setup: ({ site: { siteMetadata }, ...rest }) => ({
    ...siteMetadata, ...rest
  }),

  // Create a default RSS feed. Others may be added by using the format below.
  feeds: [
    {
      query: `
      {
        allMarkdownRemark(
          limit: 1000,
          sortBy: {
            order: DESC,
            fields: [frontmatter___date]
          },
          frontmatter: {
            draft: { ne: true }
          }
        ) {
          edges {
            node {
              frontmatter {
                title
                date
              }
              fields {
                slug
              }
              excerpt
              html
            }
          }
        }
      }
    `,

      // Where we will save the feed generated by this query.
      output: `rss.xml`,
    },
  ],
}
