// Returns the options that will be used to create each item
// in the feed that is generated by node-rss. Each feed may
// provide its own `serialize` function, but this provides
// smart defaults that should work for most folks.
//
// The function receives one argument: the result of the feed's query
export default function serialize({
  site,
  entries,
}) {
  return entries.edges.map(edge => {
    return {
      ...edge.node.frontmatter,
      description: edge.node.excerpt,
      url: site.siteMetadata.siteUrl + edge.node.fields.slug,
      guid: site.siteMetadata.siteUrl + edge.node.fields.slug,
      custom_elements: [{ "content:encoded": edge.node.html }],
    }
  })
}
