### Type definitions saved at 2021-04-29T15:27:17.706Z ###

type File implements Node @dontInfer {
  sourceInstanceName: String!
  absolutePath: String!
  relativePath: String!
  extension: String!
  size: Int!
  prettySize: String!
  modifiedTime: Date! @dateformat
  accessTime: Date! @dateformat
  changeTime: Date! @dateformat
  birthTime: Date! @dateformat
  root: String!
  dir: String!
  base: String!
  ext: String!
  name: String!
  relativeDirectory: String!
  dev: Int!
  mode: Int!
  nlink: Int!
  uid: Int!
  gid: Int!
  rdev: Int!
  ino: Float!
  atimeMs: Float!
  mtimeMs: Float!
  ctimeMs: Float!
  atime: Date! @dateformat
  mtime: Date! @dateformat
  ctime: Date! @dateformat
  birthtime: Date @deprecated(reason: "Use `birthTime` instead")
  birthtimeMs: Float @deprecated(reason: "Use `birthTime` instead")
}

type Directory implements Node @dontInfer {
  sourceInstanceName: String!
  absolutePath: String!
  relativePath: String!
  extension: String!
  size: Int!
  prettySize: String!
  modifiedTime: Date! @dateformat
  accessTime: Date! @dateformat
  changeTime: Date! @dateformat
  birthTime: Date! @dateformat
  root: String!
  dir: String!
  base: String!
  ext: String!
  name: String!
  relativeDirectory: String!
  dev: Int!
  mode: Int!
  nlink: Int!
  uid: Int!
  gid: Int!
  rdev: Int!
  ino: Float!
  atimeMs: Float!
  mtimeMs: Float!
  ctimeMs: Float!
  atime: Date! @dateformat
  mtime: Date! @dateformat
  ctime: Date! @dateformat
  birthtime: Date @deprecated(reason: "Use `birthTime` instead")
  birthtimeMs: Float @deprecated(reason: "Use `birthTime` instead")
}

type Site implements Node @dontInfer {
  buildTime: Date @dateformat
  siteMetadata: SiteSiteMetadata
  port: Int
  host: String
  polyfill: Boolean
  pathPrefix: String
}

type SiteSiteMetadata {
  title: String
  description: String
}

type SiteFunction implements Node @dontInfer {
  apiRoute: String!
  originalFilePath: String!
  relativeCompiledFilePath: String!
  absoluteCompiledFilePath: String!
  matchPath: String
}

type SitePage implements Node @dontInfer {
  path: String!
  component: String!
  internalComponentName: String!
  componentChunkName: String!
  matchPath: String
}

type MarkdownHeading {
  id: String
  value: String
  depth: Int
}

enum MarkdownHeadingLevels {
  h1
  h2
  h3
  h4
  h5
  h6
}

enum MarkdownExcerptFormats {
  PLAIN
  HTML
  MARKDOWN
}

type MarkdownWordCount {
  paragraphs: Int
  sentences: Int
  words: Int
}

type MarkdownRemark implements Node @childOf(mimeTypes: ["text/markdown", "text/x-markdown"], types: ["ContentfulNodeTypeText"]) @derivedTypes @dontInfer {
  frontmatter: MarkdownRemarkFrontmatter
  excerpt: String
  rawMarkdownBody: String
}

type MarkdownRemarkFrontmatter {
  title: String
}

interface ContentfulInternalReference implements Node {
  id: ID!
  sys: ContentfulInternalSys
}

type ContentfulInternalSys {
  type: String!
  id: String!
  spaceId: String!
  environmentId: String!
  contentType: ContentfulContentType @link(by: "id", from: "contentType___NODE")
  firstPublishedAt: Date!
  publishedAt: Date!
  publishedVersion: Int!
  locale: String!
}

type ContentfulContentType implements Node @derivedTypes @dontInfer {
  name: String!
  displayField: String!
  description: String!
  sys: ContentfulContentTypeSys
}

type ContentfulContentTypeSys {
  type: String
  id: String
  locale: String
  spaceId: String
  environmentId: String
  firstPublishedAt: Date @dateformat
  publishedAt: Date @dateformat
  publishedVersion: Int
}

interface ContentfulEntry implements Node {
  id: ID!
  sys: ContentfulInternalSys
}

type ContentfulAsset implements ContentfulInternalReference & Node @dontInfer {
  file: ContentfulAssetFile
  title: String
  description: String
  sys: ContentfulInternalSys
}

type ContentfulAssetFile {
  url: String
  details: ContentfulAssetFileDetails
  fileName: String
  contentType: String
}

type ContentfulAssetFileDetails {
  size: Int
  image: ContentfulAssetFileDetailsImage
}

type ContentfulAssetFileDetailsImage {
  width: Int
  height: Int
}

type ContentfulNodeTypeRichText @dontInfer {
  raw: JSON
  references: [ContentfulInternalReference]
}

type ContentfulNodeTypeLocation @dontInfer {
  lat: Float!
  lon: Float!
}

type ContentfulNodeTypeText implements Node @dontInfer {
  raw: String!
}

type ContentfulNumber implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  integer: Int
  decimal: Float
}

type ContentfulText implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  short: String
  shortList: [String]
  longPlain: ContentfulNodeTypeText @link(by: "id", from: "longPlain___NODE")
  longMarkdown: ContentfulNodeTypeText @link(by: "id", from: "longMarkdown___NODE")
}

type ContentfulMediaReference implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  one: ContentfulAsset @link(by: "id", from: "one___NODE")
  many: [ContentfulAsset] @link(by: "id", from: "many___NODE")
}

type ContentfulBoolean implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  boolean: Boolean
}

type ContentfulDate implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  date: Date @dateformat
  dateTime: Date @dateformat
  dateTimeTimezone: Date @dateformat
}

type ContentfulLocation implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  location: ContentfulNodeTypeLocation
}

type ContentfulJson implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  json: JSON
}

type ContentfulRichText implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  richText: ContentfulNodeTypeRichText
}

type ContentfulContentReference implements ContentfulInternalReference & ContentfulEntry & Node @dontInfer {
  sys: ContentfulInternalSys
  title: String
  one: ContentfulEntry @link(by: "id", from: "one___NODE")
  many: [ContentfulEntry] @link(by: "id", from: "many___NODE")
}