export { GatsbyImage } from "./components/gatsby-image.server"
export { GatsbyImageProps } from "./components/gatsby-image.browser"
export { Placeholder } from "./components/placeholder"
export { MainImage } from "./components/main-image"
export { StaticImage } from "./components/static-image.server"
