export const contentTypes = [
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `number`,
      type: `ContentType`,
      createdAt: `2021-03-01T16:59:23.010Z`,
      updatedAt: `2021-05-21T11:20:58.851Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 5,
    },
    displayField: `title`,
    name: `Number`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `integer`,
        name: `Integer`,
        type: `Integer`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `integerLocalized`,
        name: `Integer Localized`,
        type: `Integer`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `decimal`,
        name: `Decimal`,
        type: `Number`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `decimalLocalized`,
        name: `Decimal Localized`,
        type: `Number`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `text`,
      type: `ContentType`,
      createdAt: `2021-03-01T17:02:35.612Z`,
      updatedAt: `2021-05-21T10:48:06.210Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 3,
    },
    displayField: `title`,
    name: `Text`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `short`,
        name: `Short`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `shortLocalized`,
        name: `Short Localized`,
        type: `Symbol`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `shortList`,
        name: `Short List`,
        type: `Array`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Symbol`,
          validations: [],
        },
      },
      {
        id: `shortListLocalized`,
        name: `Short List Localized`,
        type: `Array`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Symbol`,
          validations: [],
        },
      },
      {
        id: `longPlain`,
        name: `Long Plain`,
        type: `Text`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `longMarkdown`,
        name: `Long Markdown`,
        type: `Text`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `longLocalized`,
        name: `Long Localized`,
        type: `Text`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `mediaReference`,
      type: `ContentType`,
      createdAt: `2021-03-01T17:03:21.639Z`,
      updatedAt: `2021-05-21T11:11:20.265Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 8,
    },
    displayField: `title`,
    name: `Media Reference`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `one`,
        name: `One`,
        type: `Link`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        linkType: `Asset`,
      },
      {
        id: `oneLocalized`,
        name: `One Localized`,
        type: `Link`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
        linkType: `Asset`,
      },
      {
        id: `many`,
        name: `Many`,
        type: `Array`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Link`,
          validations: [],
          linkType: `Asset`,
        },
      },
      {
        id: `manyLocalized`,
        name: `Many Localized`,
        type: `Array`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Link`,
          validations: [],
          linkType: `Asset`,
        },
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `boolean`,
      type: `ContentType`,
      createdAt: `2021-03-01T17:05:40.030Z`,
      updatedAt: `2021-05-21T10:32:45.505Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 3,
    },
    displayField: `title`,
    name: `Boolean`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `boolean`,
        name: `Boolean`,
        type: `Boolean`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `booleanLocalized`,
        name: `Boolean Localized`,
        type: `Boolean`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `date`,
      type: `ContentType`,
      createdAt: `2021-03-01T17:07:02.629Z`,
      updatedAt: `2021-05-20T18:16:28.584Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 2,
    },
    displayField: `title`,
    name: `Date`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `date`,
        name: `Date`,
        type: `Date`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `dateTime`,
        name: `Date Time`,
        type: `Date`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `dateTimeTimezone`,
        name: `Date Time Timezone`,
        type: `Date`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `dateLocalized`,
        name: `Date Localized`,
        type: `Date`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `location`,
      type: `ContentType`,
      createdAt: `2021-03-01T17:09:20.579Z`,
      updatedAt: `2021-05-21T10:37:52.205Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 2,
    },
    displayField: `title`,
    name: `Location`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `location`,
        name: `Location`,
        type: `Location`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `locationLocalized`,
        name: `Location Localized`,
        type: `Location`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `json`,
      type: `ContentType`,
      createdAt: `2021-03-01T17:09:56.970Z`,
      updatedAt: `2021-05-21T10:36:57.432Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 2,
    },
    displayField: `title`,
    name: `JSON`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `json`,
        name: `JSON`,
        type: `Object`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `jsonLocalized`,
        name: `JSON Localized`,
        type: `Object`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `richText`,
      type: `ContentType`,
      createdAt: `2021-03-01T17:11:01.406Z`,
      updatedAt: `2021-11-05T12:56:39.942Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 7,
    },
    displayField: `title`,
    name: `Rich Text`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `richText`,
        name: `Rich Text`,
        type: `RichText`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `richTextLocalized`,
        name: `Rich Text Localized`,
        type: `RichText`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `richTextValidated`,
        name: `Rich Text Validated`,
        type: `RichText`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `contentReference`,
      type: `ContentType`,
      createdAt: `2021-03-02T09:17:08.210Z`,
      updatedAt: `2021-05-21T10:36:34.506Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 7,
    },
    displayField: `title`,
    name: `Content Reference`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `one`,
        name: `One`,
        type: `Link`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        linkType: `Entry`,
      },
      {
        id: `oneLocalized`,
        name: `One Localized`,
        type: `Link`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
        linkType: `Entry`,
      },
      {
        id: `many`,
        name: `Many`,
        type: `Array`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Link`,
          validations: [
            {
              linkContentType: [`contentReference`, `number`, `text`],
            },
          ],
          linkType: `Entry`,
        },
      },
      {
        id: `manyLocalized`,
        name: `Many Localized`,
        type: `Array`,
        localized: true,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Link`,
          validations: [],
          linkType: `Entry`,
        },
      },
    ],
  },
  {
    sys: {
      space: {
        sys: {
          type: `Link`,
          linkType: `Space`,
          id: `k8iqpp6u0ior`,
        },
      },
      id: `validatedContentReference`,
      type: `ContentType`,
      createdAt: `2021-05-20T15:29:49.734Z`,
      updatedAt: `2021-05-20T15:33:26.620Z`,
      environment: {
        sys: {
          id: `master`,
          type: `Link`,
          linkType: `Environment`,
        },
      },
      revision: 4,
    },
    displayField: `title`,
    name: `ValidatedContentReference`,
    description: ``,
    fields: [
      {
        id: `title`,
        name: `Title`,
        type: `Symbol`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
      },
      {
        id: `oneItemSingleType`,
        name: `One Item: Single Type`,
        type: `Link`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        linkType: `Entry`,
        validations: [
          {
            linkContentType: [`text`],
          },
        ],
      },
      {
        id: `oneItemManyTypes`,
        name: `One Item: Many Types`,
        type: `Link`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        linkType: `Entry`,
        validations: [
          {
            linkContentType: [`number`, `text`],
          },
        ],
      },
      {
        id: `oneItemAllTypes`,
        name: `One Item: All Types`,
        type: `Link`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        linkType: `Entry`,
      },
      {
        id: `multipleItemsSingleType`,
        name: `Multiple Items: Single Type`,
        type: `Array`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Link`,
          validations: [
            {
              linkContentType: [`text`],
            },
          ],
          linkType: `Entry`,
        },
      },
      {
        id: `multipleItemsManyTypes`,
        name: `Multiple Items: Many Types`,
        type: `Array`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Link`,
          validations: [
            {
              linkContentType: [`number`, `text`],
            },
          ],
          linkType: `Entry`,
        },
      },
      {
        id: `multipleItemsAllTypes`,
        name: `Multiple Items: All Types`,
        type: `Array`,
        localized: false,
        required: false,
        disabled: false,
        omitted: false,
        items: {
          type: `Link`,
          validations: [],
          linkType: `Entry`,
        },
      },
    ],
  },
]
