import { page } from "../../../shared-data/head-function-export.js"

it.only(`head function export should get all page properties`, () => {
  cy.visit(page.allProps)
  cy.getTestElement(`location.origin`)
    .invoke(`attr`, `content`)
    .should(`equal`, `http://localhost:8000`)
  cy.getTestElement(`pageContext`)
    .invoke(`attr`, `content`)
    .should(`not.be.undefined`)
  cy.getTestElement(`pageResources.page.componentChunkName`)
    .invoke(`attr`, `content`)
    .should(`equal`, `component---src-pages-head-function-export-all-props-js`)
  cy.getTestElement(`params`)
    .invoke(`attr`, `content`)
    .should(`not.be.undefined`)
  cy.getTestElement(`path`)
    .invoke(`attr`, `content`)
    .should(`equal`, `/head-function-export/all-props/`)
  cy.getTestElement(`uri`)
    .invoke(`attr`, `content`)
    .should(`equal`, `/head-function-export/all-props`)
})
