### Type definitions saved at 2019-12-12T13:05:42.017Z ###

type File implements Node @dontInfer {
  sourceInstanceName: String!
  absolutePath: String!
  relativePath: String!
  extension: String!
  size: Int!
  prettySize: String!
  modifiedTime: Date! @dateformat
  accessTime: Date! @dateformat
  changeTime: Date! @dateformat
  birthTime: Date! @dateformat
  root: String!
  dir: String!
  base: String!
  ext: String!
  name: String!
  relativeDirectory: String!
  dev: Int!
  mode: Int!
  nlink: Int!
  uid: Int!
  gid: Int!
  rdev: Int!
  ino: Float!
  atimeMs: Float!
  mtimeMs: Float!
  ctimeMs: Float!
  atime: Date! @dateformat
  mtime: Date! @dateformat
  ctime: Date! @dateformat
  birthtime: Date @deprecated(reason: "Use `birthTime` instead")
  birthtimeMs: Float @deprecated(reason: "Use `birthTime` instead")
}

type Directory implements Node @dontInfer {
  sourceInstanceName: String!
  absolutePath: String!
  relativePath: String!
  extension: String!
  size: Int!
  prettySize: String!
  modifiedTime: Date! @dateformat
  accessTime: Date! @dateformat
  changeTime: Date! @dateformat
  birthTime: Date! @dateformat
  root: String!
  dir: String!
  base: String!
  ext: String!
  name: String!
  relativeDirectory: String!
  dev: Int!
  mode: Int!
  nlink: Int!
  uid: Int!
  gid: Int!
  rdev: Int!
  ino: Float!
  atimeMs: Float!
  mtimeMs: Float!
  ctimeMs: Float!
  atime: Date! @dateformat
  mtime: Date! @dateformat
  ctime: Date! @dateformat
  birthtime: Date @deprecated(reason: "Use `birthTime` instead")
  birthtimeMs: Float @deprecated(reason: "Use `birthTime` instead")
}

type ChildOfParent_ChildDeletionForTransformer implements Node @dontInfer {
  foo: String
}

type ChildOfParent_ParentDeletionForTransformer implements Node @dontInfer {
  foo: String
}

type Parent_ChildDeletionForFields implements Node @derivedTypes @dontInfer {
  foo: String
  fields: Parent_ChildDeletionForFieldsFields
}

type Parent_ChildDeletionForFieldsFields {
  foo1: String
}

type Parent_ChildDeletionForTransformer implements Node @dontInfer {
  foo: String
}

type Parent_ParentDeletionForTransformer implements Node @dontInfer {
  foo: String
}

type Parent_ChildAdditionForFields implements Node @dontInfer {
  foo: String
}

type Parent_ChildAdditionForTransformer implements Node @dontInfer {
  foo: String
}

type Deletion implements Node @dontInfer {
  foo: String
}

type Parent_ChildChangeForFields implements Node @derivedTypes @dontInfer {
  foo: String
  fields: Parent_ChildChangeForFieldsFields
}

type Parent_ChildChangeForFieldsFields {
  foo1: String
}

type Parent_ParentChangeForFields implements Node @derivedTypes @dontInfer {
  foo: String
  fields: Parent_ParentChangeForFieldsFields
}

type Parent_ParentChangeForFieldsFields {
  foo: String
}

type ChildOfParent_ChildChangeForTransformer implements Node @dontInfer {
  foo: String
}

type Parent_ChildChangeForTransformer implements Node @dontInfer {
  foo: String
}

type ChildOfParent_ParentChangeForTransformer implements Node @dontInfer {
  foo: String
}

type Parent_ParentChangeForTransformer implements Node @dontInfer {
  foo: String
}

type IndependentChanging implements Node @dontInfer {
  foo: String
}

type IndependentStable implements Node @dontInfer {
  foo: String
}